### ISSUE TITLE
發布的jar檔移到gh-pages分支 & Maven

### ISSUE THREAD

**Issue by abc9070410** [abc9070410/JComicDownloader#10]
抱歉因為我不知道contributors之間怎麼溝通，所以就開新issue來跟你們說一下，我現在把發布的jar檔放到gh-pages分支，跟source code做區隔，這樣以後維護可能比較方便。

不知道Puneyrf Cbba和icearea你們覺得如何? 有其他意見也可以在這邊討論喔~

**Comment by hkgsherlock** [comment]
原本就想寫個 issue 是說明重整整個 repo 的檔案…（我用 IntelliJ 的，NetBeans-specific 的一堆檔案實在是 囧rz）

不太明白為何這樣分開放會有什麼的「方便」。照 [`manifest.mf`](https://github.com/abc9070410/JComicDownloader/blob/master/manifest.mf) 的內容，似乎放到 `/lib` 會還好

如果其他人（例如用家）需要取得這些的 dependencies 的話，導引他們到 `/lib` 那裡好像會比較好

**Comment by abc9070410** [comment]
恩你願意重整的話歡迎重整，我只要NetBeans可以build都OK。之前有個Kenny有創另一個分支放改寫的maven專案，不過他後來好像自己刪掉了...

喔好那我jar還是放在master分支，只另外開一個release資料夾裡面放jar壓縮檔跟JComicDownloader.jar

**Comment by hkgsherlock** [comment]
maven 是什麼來的？

> 另外開一個release資料夾裡面放jar壓縮檔跟JComicDownloader.jar

真的不使用[GitHub 的 releases & tags 功能](https://github.com/abc9070410/JComicDownloader/releases)嗎？

**Comment by abc9070410** [comment]
Maven是這個: https://maven.apache.org/guides/introduction/introduction-to-the-pom.html
我也沒研究...

!! 第一次Github知道有release這個功能，看起來正式多了，就用這個啦，我再研究一下。

**Comment by Kennyl** [comment]
因為我rebase 乱了，所以刪掉了。
放在gh_page的原因我想放一些 third party jar  給程式下載。
maven 改動，有時間我會repull 的。

**Comment by hkgsherlock** [comment]
用 dep 的話 JGit 會行
不用 dep 的話直接在 html 選定所有檔案也行

但總之在不同地方都放一堆 dep 的 jar 感覺會浪費空間也有不同步問題，慢慢想再決定解決方法

maven 的就隨你吧

**Comment by Kennyl** [comment]
因為maven online repository上有一些 3rd party jar 比google sites上的新，所以才放上去。
所以如果改用maven，我想用新的jar , 當然如果 用offline 也是可以，還請大家的看法。

**Comment by hkgsherlock** [comment]
直接將 Google Sites 上的關掉，然後全部由 GitHub branch `main` 的 `/lib` 取得，如何？
反正 project 中 dependencies 也是全部由 `/lib` 讀取的
（還有就是可以 sub-module 之類）

by the way,
[`GET https://api.github.com/repos/abc9070410/JComicDownloader/contents/lib`](https://developer.github.com/v3/repos/contents/)
```
[
    {
        "name":"jaudiotagger-2.0.4-20111207.115108-15.jar",
        "path":"lib/jaudiotagger-2.0.4-20111207.115108-15.jar",
        "sha":"63a312b969e3100047bbb5309ca254397aa6b405",
        "size":869132,
        "url":"https://api.github.com/repos/abc9070410/JComicDownloader/contents/lib/jaudiotagger-2.0.4-20111207.115108-15.jar?ref=master",
        "html_url":"https://github.com/abc9070410/JComicDownloader/blob/master/lib/jaudiotagger-2.0.4-20111207.115108-15.jar",
        "git_url":"https://api.github.com/repos/abc9070410/JComicDownloader/git/blobs/63a312b969e3100047bbb5309ca254397aa6b405",
        "download_url":"https://raw.githubusercontent.com/abc9070410/JComicDownloader/master/lib/jaudiotagger-2.0.4-20111207.115108-15.jar",
        "type":"file",
        "_links":{
            "self":"https://api.github.com/repos/abc9070410/JComicDownloader/contents/lib/jaudiotagger-2.0.4-20111207.115108-15.jar?ref=master",
            "git":"https://api.github.com/repos/abc9070410/JComicDownloader/git/blobs/63a312b969e3100047bbb5309ca254397aa6b405",
            "html":"https://github.com/abc9070410/JComicDownloader/blob/master/lib/jaudiotagger-2.0.4-20111207.115108-15.jar"
        }
    }
]
```

megusta.jpg

**Comment by Kennyl** [comment]
可以的。
如果是 maven , dependency 會從http://mvnrepository.com/ 下載到 IDE，好像 android 用gradle 差不多一樣。
或者我pull 一個maven mockup 給大家看一看先。

**Comment by Kennyl** [comment]
有時間看一看吧。

https://github.com/Kennyl/JComicDownloader/tree/feature/maven
intellj  build 請用import project , maven project , execute package goal
![screen shot 2015-07-01 at 12 41 25 pm](https://cloud.githubusercontent.com/assets/1933134/8447653/97cf472a-1fee-11e5-8223-06d201e70471.png)

**Comment by Kennyl** [comment]
http://stackoverflow.com/questions/3329041/best-practice-to-store-jar-files-in-vcs-svn-git

其實我當gh_pages 是static pages 放jar.
最终可能試git lfs

**Comment by hkgsherlock** [comment]
> 恩你願意重整的話歡迎重整，我只要NetBeans可以build都OK

#11, #12 

如何 create project 會另外寫就是了

**Comment by Kennyl** [comment]
我直接push 了我的maven 改動去了master, 我想我不能接受自己手動rebase 這了，已經五次了。

**Comment by hkgsherlock** [comment]
ok 的

那[這篇](../wiki/Building-this-project)改為以 maven project 的方法就行了對吧

**Comment by Kennyl** [comment]
我會慢慢幫手改這wiki.
因為我多數是git clone 才開IDE import / open maven project 的，不用new project 的, 而且又可以cross IDE.

**Comment by abc9070410** [comment]
> 直接將 Google Sites 上的關掉，然後全部由 GitHub branch main 的 /lib 取得，如何？

同意，我之後也會陸續把Google Site還有用的東西搬過來。
至於專案重整那些細節你們討論就好，我完全外行，哈哈。

**Comment by hkgsherlock** [comment]
邊做邊學就行

**Comment by Kennyl** [comment]
不要放jar 在git 的master branch 當jar obsolete 不可以用删branch方法清理這些對dvcs構成負擔的binary 檔

**Comment by hkgsherlock** [comment]
那是否應該是用你之前提及的 Git LFS 用 pointer 儲存？

**Comment by Kennyl** [comment]
應該、但我不知道github何時開通給我。
放在gh_pages branch 只是暫時用.

**Comment by Kennyl** [comment]
另如果用maven 管理可以自動生成3rdParty的版權訊息。你可試一下mvn site生成。
放在github 是為了兼容本程式的自動下载。

**Comment by hkgsherlock** [comment]
FYI about GitHub LFS:
https://github.com/blog/2069-git-large-file-storage-v1-0
