### ISSUE TITLE
DM5 有時下載錯誤

### ISSUE THREAD

**Issue by Archer515** [abc9070410/JComicDownloader#101]
使用的版本是 `v5.30.170505`。

1. 99770系列無法下載了。
2. DM5網站偶爾會出現下載錯誤(不是每一個都會，但機率不低)。出現錯誤的漫畫可能內容依然正常下載，也可能直接跳掉章節。

我只是個重度使用者，感謝各位大大

**Comment by hkgsherlock** [comment]
#73 
如果 99770 那邊直接用瀏覽器都不能開啟頁面的話，才再 fix 吧

DM5 那邊再看

**Comment by hkgsherlock** [comment]
#73 
如果 99770 那邊直接用瀏覽器都不能開啟頁面的話，才再 fix 吧

DM5 那邊再看

**Comment by dxzy** [comment]
dm5的確會有錯誤 例如最近試著抓 http://tel.dm5.com/manhua-gebulinshashou/ 
舊版會抓成上一個DM5的漫畫 新版直接錯誤 倒不是每個都會出錯 就特定幾個

**Comment by hkgsherlock** [comment]
判斷 99770 issue invalid

**Comment by hkgsherlock** [comment]
tmd 用個 `Accept-Language: zh-TW,zh;q=0.8,en-US;q=0.6,en;q=0.4` 就能起死回生也太好笑了吧
可能是網站的 PHP 要判斷地區時會用到，找不到這個 Header 就出 404（怎麼不是出 500……🤣

已經試過你的那個《哥布林殺手》，下載後肉眼檢查 + 以下的 PowerShell cmdlet 計數：
```ls -directory | % { $a = 0; ls -File $_.name | % { $b = [int]$_.BaseName; if (($a + 1) -ne $b) {break}; $a=$b }; echo "$_ : $a" }```

```
番外 : 4
第001卷 : 95
第001話 : 50
第002話 : 49
第003話 : 40
第004話 : 35
第005話 : 35
第006話 : 37
第007話 : 30
第008話 : 37
第009話 : 33
```

🤔
