### ISSUE TITLE
[8comic] 無法看出己下載的集數; 抓錯漫畫名稱

### ISSUE THREAD

**Issue by ballcat** [abc9070410/JComicDownloader#103]
之前的版本 , 可以看出己下載的集數 (灰色)

可是這次版本更新後 , 不管那個書籤點選 "加入到下載任務" , 出現的集數看不出來己下的
然後下載回來的目錄位置也不對

例如漫畫我是集中放在 d:\down , 程式設定也是在  d:\down
![1](https://cloud.githubusercontent.com/assets/13775779/26823183/4b55575e-4adf-11e7-8b5c-2dfebd4feeb7.jpg)

但是隨便一本下載列出的都是沒下過` (以一拳超人為例)
![2](https://cloud.githubusercontent.com/assets/13775779/26823186/4fac4808-4adf-11e7-8fff-2446c93b1a46.jpg)

而實際上目錄中除了最新的 , 其他都下過了
![3](https://cloud.githubusercontent.com/assets/13775779/26823188/5217bb86-4adf-11e7-88bd-49c25ff623bf.jpg)

然後只下最後一集(116話) , 卻是把下載來的目錄 , 放在 D:\down\第116話
![4](https://cloud.githubusercontent.com/assets/13775779/26823194/55840d1a-4adf-11e7-90ca-895e7410162c.jpg)

**Comment by Archer515** [comment]
目前8comic改版後我也是遇到這個問題

**Comment by Clarkliu0919** [comment]
應該是8comic改版了 沒辦法抓到漫畫名稱 每次抓檔都必須手動修改

**Comment by erorzero** [comment]
8comic有這問題 dm5則沒有

**Comment by hkgsherlock** [comment]
那就是說 8comic 要重寫 DOM select query 了，我看看

**Comment by hkgsherlock** [comment]
標題那邊直接在 DOM 裡取 `<title>` 然後用 RegEx 擷取作罷

**Comment by hkgsherlock** [comment]
>然後只下最後一集(116話) , 卻是把下載來的目錄 , 放在 D:\down\第116話
原本問題就是 e.g.:
`E:\prog\JComicDownloader\debug\down\{漫畫名稱}\{集數}\000.jpg`
因為沒有漫畫名稱就變成
``E:\prog\JComicDownloader\debug\down\\第116話\000.jpg` in which `\\` == `\`
如果漫畫標題能夠成功取得的話，就應該不會產生錯儲存位置的問題

**Comment by hkgsherlock** [comment]
先把這個 issue 當成只 report 8comic 的問題了，反請 DM5 的 issues 還有很多 ( #96 , #101 )
要 PR fix 起來會比較方便
