### ISSUE TITLE
DM5有四部漫畫無法下載

### ISSUE THREAD

**Issue by crazyday7** [abc9070410/JComicDownloader#114]
http://www.dm5.com/manhua-yuedingdemenghuandao/
http://www.dm5.com/manhua-zhibumiedeni/
http://www.dm5.com/manhua-yinweiwoshikaiwuqidiandedashu/
http://www.dm5.com/manhua-shigewendezuijiangxianzhe-shijiezuijiangdexianzheweilebiandegengqiangerzhuanshengle/
版本是：5.30.170922

**Comment by crazyday7** [comment]
又發現一部無法下載
http://www.dm5.com/manhua-shimodelisi/

**Comment by Archer515** [comment]
基本上dm5全部都不能下了
不過是今天才這樣

**Comment by Archer515** [comment]
今天dm5更新的又可以了
昨天更新的還是不行，可能是昨天網站出錯吧
