### ISSUE TITLE
dm5的所有漫畫都無法解析

### ISSUE THREAD

**Issue by AA891117** [abc9070410/JComicDownloader#120]
請問是什麼的問題，我的電腦最近更新到win10，以前在win7都是可以的

**Comment by ballcat** [comment]
我剛試了新的 v5.30.171116 版本

dm5 的可以解析及下載
8comic 的還是不行

**Comment by AA891117** [comment]
我今天試試看，如果還是不行會傳圖片給您看，謝謝

2017年11月20日 下午12:22，"ballcat" <notifications@github.com>寫道：

**Comment by AA891117** [comment]
您好，還是不行(提供您網址檢查)
1.http://www.dm5.com/manhua-shijizhiling/
2.http://www.dm5.com/manhua-qiyuanzui/
以下是兩個網址的截圖
麻煩您了 ! 謝謝。

俞政廷 <kristyu891117@gmail.com> 於 2017年11月20日 下午12:26 寫道：

**Comment by AA891117** [comment]
不好意思，剛剛的版本不對，這個才是

俞政廷 <kristyu891117@gmail.com> 於 2017年11月20日 下午11:07 寫道：

**Comment by Kennyl** [comment]
1. 可以下載
<img width="617" alt="screen shot 2017-11-21 at 3 33 09 pm" src="https://user-images.githubusercontent.com/1933134/33059931-657d8a04-ced1-11e7-85d3-fa6d86120e29.png">
2.
<img width="205" alt="screen shot 2017-11-21 at 3 34 48 pm" src="https://user-images.githubusercontent.com/1933134/33059984-932d72a2-ced1-11e7-8fed-e189c559fc07.png">

**Comment by ballcat** [comment]
我試也是可以
![1116](https://user-images.githubusercontent.com/13775779/33109788-8f13c45c-cf7e-11e7-887a-0472cd568132.jpg)

**Comment by AA891117** [comment]
所以和作業系統有關嗎？
JAVA也有裝好，但就是和照片上的一樣是無法解析

2017年11月22日 下午12:13，"ballcat" <notifications@github.com>寫道：

我試也是可以
[image: 1116]
<https://user-images.githubusercontent.com/13775779/33109788-8f13c45c-cf7e-11e7-887a-0472cd568132.jpg>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/abc9070410/JComicDownloader/issues/120#issuecomment-346238411>,
or mute the thread

**Comment by AA891117** [comment]
請問是複製網址後貼上，然後按下載嗎？
漫畫下載器的執行檔要移動嗎？還是軟體直接下載後就執行了？
我今天用一臺win7的電腦也失敗

2017年11月22日 下午12:23，kristyu891117@gmail.com寫道：

**Comment by abc9070410** [comment]
可以試試新版本:
https://github.com/abc9070410/JComicDownloader/releases/tag/v5.30.180211
如果還有問題 , 請貼上無法下載的網址 , 謝啦

**Comment by AA891117** [comment]
謝謝您

2018年2月11日 下午4:14，"surveyorK" <notifications@github.com>寫道：
