### ISSUE TITLE
DMZJ陣亡

### ISSUE THREAD

**Issue by dxzy** [abc9070410/JComicDownloader#123]
如圖 https://i.imgur.com/ccawXOz.png
抓到整個頁面無關的項目 確認無法點 
應該網站剛改版 大概在改版後的漫畫所有都會這樣無法抓取 因為之前的項目還能抓

**Comment by abc9070410** [comment]
可以試試新版本:
https://github.com/abc9070410/JComicDownloader/releases/tag/v5.30.180211
如果還有問題 , 請貼上無法下載的網址 , 謝啦
