### ISSUE TITLE
DM5更新 無法下載

### ISSUE THREAD

**Issue by iso0000** [abc9070410/JComicDownloader#125]
DM5網站更新後 現在漫畫都不能下載

**Comment by jack050518** [comment]
一樣狀況
DM5更新後全部都無法下載

**Comment by sanbis1983** [comment]
DM5 無法下載 +1

**Comment by cathylin146** [comment]
一樣狀況，DM5更新後全部都無法下載

**Comment by Archer515** [comment]
真的只能等大大普渡眾生QAQ

**Comment by AA891117fish** [comment]
+1

**Comment by cathylin146** [comment]
DM5網站更新後，更新的漫畫都沒有做"分頁"!!!
所以DM5幾乎可以說是"廢了"!!!

**Comment by abc9070410** [comment]
可以試試新版本:
https://github.com/abc9070410/JComicDownloader/releases/tag/v5.30.180211
如果還有問題 , 請貼上無法下載的網址 , 謝啦

**Comment by cathylin146** [comment]
感謝abc9070410 的提供及告知新版本。
http://www.dm5.com/manhua-shijizhiling/ 第250話已試測下載完成。

**Comment by iso0000** [comment]
感謝abc9070410的幫忙及更新
