### ISSUE TITLE
目前還有什麼漫畫網是可以下載的嗎?

### ISSUE THREAD

**Issue by Archer515** [abc9070410/JComicDownloader#127]
自從前幾天dm5跟新不能載之後
這幾天不知道要怎麼辦，跟戒毒一樣
以前的大神們似乎都沒有在關注了
不知道有沒有同好知道現在還有哪個網站可以正常下載的？

**Comment by dxzy** [comment]
兩周過去 dmzj都堆了三百個未下載分頁.....

**Comment by sanbis1983** [comment]
dmzj 好像只能下載三張突然後就停了~
ck101 好像還可以？

**Comment by cathylin146** [comment]
dm5更新後的漫畫都是沒有做"分頁"，所以dm5幾乎是等於"廢了"!!!

**Comment by Archer515** [comment]
感恩abc9070410，讚嘆 abc9070410 。
因為abc9070410 這世界才有了光。
 abc9070410 大大更新了，大家可以專心看漫畫直到DM5再改版了。
