### ISSUE TITLE
一直顯示下載錯誤

### ISSUE THREAD

**Issue by AA891117fish** [abc9070410/JComicDownloader#128]
最近DM5的漫畫都載不了，會一直顯示下載錯誤。

**Comment by sanbis1983** [comment]
你沒看前面的內容嗎？
DM5 更新以後就失效了

**Comment by abc9070410** [comment]
可以試試新版本:
https://github.com/abc9070410/JComicDownloader/releases/tag/v5.30.180211
如果還有問題 , 請貼上無法下載的網址 , 謝啦
