### ISSUE TITLE
動漫屋不能下載!!

### ISSUE THREAD

**Issue by ckes97007** [abc9070410/JComicDownloader#129]
去年我還能從動漫屋下載漫畫，但今年要在下載動漫屋的漫畫時卻不能下載了，一直顯示下載錯誤。

**Comment by abc9070410** [comment]
可以試試新版本:
https://github.com/abc9070410/JComicDownloader/releases/tag/v5.30.180211
如果還有問題 , 請貼上無法下載的網址 , 謝啦

**Comment by ckes97007** [comment]
謝謝，辛苦了。
