### ISSUE TITLE
动漫之家(https://manhua.dmzj.com)無法下載

### ISSUE THREAD

**Issue by potami** [abc9070410/JComicDownloader#134]
已使用新版(JComicDownloader v5.30.180211)但還是會出現以下錯誤
=================================================================
錯誤提示：
無法正確下載https://manhua.dmzj.com/xiangchengweixiaoshuojiadefangfa/！

錯誤原因：
connect timed out

錯誤發生地點：
java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
java.net.AbstractPlainSocketImpl.connect(Unknown Source)
java.net.PlainSocketImpl.connect(Unknown Source)
java.net.SocksSocketImpl.connect(Unknown Source)
java.net.Socket.connect(Unknown Source)
sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
sun.net.NetworkClient.doConnect(Unknown Source)
sun.net.www.http.HttpClient.openServer(Unknown Source)
sun.net.www.http.HttpClient.openServer(Unknown Source)
sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
java.net.HttpURLConnection.getResponseCode(Unknown Source)
sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
jcomicdownloader.tools.Common$Downloader.<init>(Common.java:3723)
jcomicdownloader.tools.Common.downloadFile(Common.java:855)
jcomicdownloader.tools.Common$Downloader.<init>(Common.java:3869)
jcomicdownloader.tools.Common.downloadFile(Common.java:855)
jcomicdownloader.tools.Common$Downloader.<init>(Common.java:3869)
jcomicdownloader.tools.Common.downloadFile(Common.java:855)
jcomicdownloader.tools.Common.downloadGZIPInputStreamFile(Common.java:506)
jcomicdownloader.module.Parse178.getAllPageString(Parse178.java:1310)
jcomicdownloader.module.RunModule.runMainProcess(RunModule.java:77)
jcomicdownloader.module.Run.runSingleParseModule(Run.java:169)
jcomicdownloader.module.Run.run(Run.java:153)

**Comment by abc9070410** [comment]
看起來是你的網路有問題
或者試試新版本:
https://github.com/abc9070410/JComicDownloader/releases/tag/v5.30.180529
