### ISSUE TITLE
新新漫画 177mh 无法解析网址

### ISSUE THREAD

**Issue by Kiyo2501** [abc9070410/JComicDownloader#139]
大大，最新版本中，新新漫画的网址无法解析了，秋修复。
![jietu20180425-201608](https://user-images.githubusercontent.com/20367301/39233876-be45eea6-48c5-11e8-82c6-2a6af5562f31.png)

**Comment by abc9070410** [comment]
試試新版本:
https://github.com/abc9070410/JComicDownloader/releases/tag/v5.30.180529

**Comment by Kiyo2501** [comment]
更新了可以解析咯超級贊~\(≧▽≦)/~
