### ISSUE TITLE
新回報狀況dm5部份改版 無法下

### ISSUE THREAD

**Issue by ok3672108** [abc9070410/JComicDownloader#148]
作者 您好 不好意思 剛遇到 狀況dm5 部份 應該有改版 有些無法下 有些部份的可以下
錯誤 https://www.dm5.com/manhua-mengyintongxuetaiguorenzhendejiaowangfangshi/
錯誤https://www.dm5.com/manhua-juruniang-x-diaosinan/

完成https://www.dm5.com/manhua-tianhuabaijian/
完成https://www.dm5.com/manhua-shenweianshazhedewomingxianbiyongzhehaiqiang/

**Comment by peiyu66** [comment]
在dm5似乎某些集數總是錯誤而致下載中斷，重新選擇集數避開有問題的，其他倒是還可以下載完成。
(我用的java是1.8.0_202)

**Comment by kanasimi** [comment]
可以增加跳過下載出錯圖片的功能
例如小弟的工具
https://github.com/kanasimi/work_crawler

不過就 @ok3672108 所提到的這兩個作品
看起來似乎是因為cookie的關係?
解決方法可見 https://github.com/kanasimi/work_crawler/blob/6215d584d63b63f3e8425aeec68f4786e753d2ae/comic.cmn-Hans-CN/dm5.js#L444

**Comment by ok3672108** [comment]
kanasimi 抱歉 對這方面外行 看不懂 想等更新版本 JComicDownloader 或 怎麼加裡面

**Comment by ok3672108** [comment]
kanasimi 抱歉 對這方面外行 看不懂 想等更新版本 JComicDownloader 或 怎麼加裡面

**Comment by ok3672108** [comment]
可是 之前沒這問題說
