### ISSUE TITLE
DM5失效回報

### ISSUE THREAD

**Issue by dxzy** [abc9070410/JComicDownloader#15]
v5.20 v5.19xx版本皆失效

DM5新建立的下載任務無法download，瞬間顯示下載錯誤，僅7/11前舊章節仍可下載。

另外同樣DM5，有的漫畫抓不到最新章節，如：
http://tel.dm5.com/manhua-guainv-qiguaidenvgaozhongshengganliqianzi/ 抓不到第8章
或是 http://tel.dm5.com/manhua-yugaofan/ 甚至缺了兩章節，

原本以為跟dmzj一樣只是JC抓取的頁面跟Web不同步導致未刷新但似乎不一樣。

※DM5某篇的留言:	
>    為什麼我這裡只顯示31話呢 
>    為什麼翻牆前看到更新了32，翻牆後就只有31 
>    翻牆後，沒翻牆的留言也看不到是個什麼鬼 
>    另一邊出32話了~~  結果這還沒出! 

留言說的神奇現象是不是跟無法下載有關呢

**Comment by hkgsherlock** [comment]
> 留言說的神奇現象
DNS/IP?

**Comment by dxzy** [comment]
IP是中華 dns主中華副google
瀏覽器沒特別切換代理(foxyproxy) 用的dns或路徑應該跟Jcomicdownloader一樣才對

**Comment by hkgsherlock** [comment]
> 但在我這邊為什麼還會出現瀏覽器/JC不同步的問題小弟就不理解了

JC parser ( ParseDM5.java ln 1412 - 1421 ) 的拆法實在是……

btw 我這期間沒空改

**Comment by dxzy** [comment]
http://i.imgur.com/53LfeVq.png
![default](https://cloud.githubusercontent.com/assets/13295999/8643055/ff9651e8-2960-11e5-9c0a-48320c1fc349.png)
如圖有八集 我火狐也讀得到圖檔 dm5真的很趣味 有人用大陸IP連過DM5嗎 會導向到www.dm5.com這樣?

**Comment by hkgsherlock** [comment]
我都說了是源碼的一堆古代部分拆法~~實在是太不堪~~跟不上現時應有的拆法就會 `8` → `7`
主要可能是以前的 `a.tg` 中 `id="cbc_1"` 後面會有 `href`，但現在放了前面，所以點算話數的數量時會錯

~~假如我重寫大概就跟 ba95173 的 [ParseEC.java](../blob/master/src/main/java/jcomicdownloader/module/ParseEC.java) 一樣用 HTML Parser 拆反倒還更穩妥這樣~~

**Comment by Kennyl** [comment]
要改寫的話,我jsoup 和 RegEx也可以幫手、但沒時間testing

2015 年 7 月 13 日 (週一)14:37 <Puneyrf Cbba> 於 notifications@github.com 寫道：

**Comment by Kennyl** [comment]
现在的是downloadFile 的content size 和browser 上有差別

**Comment by Kennyl** [comment]
现在試了 curl,httpurlconnection, 不論有無有refereer之類 會出 舊資料。
htmlunit 無cookie&refereer ,會出 新資料

**Comment by icearea** [comment]
記得之前在處理限制級抓不到的問題時有發現DM5會抓
navigator.systemLanguage||navigator.language || navigator.browserLanguage
來顯示不同網頁

**Comment by Kennyl** [comment]
okhttp 也是舊資料。
我懷疑是用httpurlconnection會出舊資料但socket 會出新資料。

**Comment by Kennyl** [comment]
我試了一次
curl --header "Accept-Language:en-US,en;q=0.8,zh-TW;q=0.6,zh;q=0.4,ja;q=0.2" tel.dm5.com/manhua-guainv-qiguaidenvgaozhongshengganliqianzi/ -o x.html
 只加了這header便成功。

**Comment by dxzy** [comment]
謝謝各位 話數正常的都成功了 it works!

**Comment by dxzy** [comment]
我真恨回報這件事 又要麻煩別人
一切都不變不是最好嗎 天底下就沒有永恆這回事 0rz

v5.20.150722b & v5.20.150715 對dm5有些無法解析 如:
http://www.dm5.com/manhua-yuanjunwuyu/ 源君物語
http://www.dm5.com/manhua-xinmeimowangdeqiyuezhe/ 新妹魔王
http://www.dm5.com/manhua-dongjing-esp/ 東京ESP
http://www.dm5.com/manhua-bianyuanxingdong/ 邊緣行動

其他大部分都可以 到處檢查之後用火狐多開隱私模式對照
『七原罪漫畫 已被列為限制漫畫，其中有部份章節可能含有暴力…』
只有被列入限制級的不能解析

**Comment by hkgsherlock** [comment]
這大概會是這個 repo 中 re-open 次數最多的 issue ![:o)](http://m4.hkgolden.com/faces/clown.gif)

源君的話，我開了以後大概是這樣：
>源君物语漫画 中有部份章节可能含有暴力、血腥、色情或不当的语言等内容，根据ctihk isp法律法规，我们将对 源君物语漫画 进行屏蔽。如果您不是该地区的用户，请点击报告此问题，给您带来不便，敬请谅解！

大概 JCD 也會不能解析，除非經 proxy

我是香港寬頻，User Agent 是 `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`

**Comment by dxzy** [comment]
應該是跟IP脫離不了關係 看到回文掛了一下台灣中華電信的proxy
一試之下源君居然可以解 (但不能下會失敗) 於是換第二個新妹解看看 "不行"
回頭重解源君又不行 接著一直試一直試 忽然某次又可以 這…太沒道理了吧
薛丁格的貓? 還是DM5的工程師是隻貓? 要嘛可以要嘛不行 哪有忽然可以然後又繼續失敗這種事

**Comment by hkgsherlock** [comment]
我那邊進入 `www.dm5.com` 會進入 `hk.dm5.com`，查看地址應該是家用 plan 用 
作~~商用~~網站 orz
你那邊台灣的話，有跟沒有用 proxy 之後會彈到哪些 host ？

**Comment by dxzy** [comment]
台灣hinet 可以連到www.dm5 也可以tel.dm5 www.dm5下翻頁有時候莫名其妙會自動導向變tel.dm5
hinet proxy結果相同 沒有特別的

我連到hk.dm5顯示是 ↓ 
>源君物语漫画 已被列为限制漫画，其中有部份章节可能含有暴力、血腥、色情或不当的语言等内容，不适合未成年观众，为保护未成年人，我们将对 源君物语漫画 进行屏蔽。如果你法定年龄已超过18岁，请点击此处继续阅读！

但一樣可以看 代表網站還是會多判斷一次IP決定顯示是 繼續閱讀or點擊回報

我不懂程式語言或html 只知道
http://hk.dm5.com 61.244.111.20 香港IP
http://www.dm5.com 107.181.249.122 美國IP
http://tel.dm5.com 61.54.29.68 中國IP 三個我都可以連 Firefox或其他瀏覽器都能看
雖然JC比較挑嘴 但總結來說我覺得還是DM5比較奇怪 古怪.....

**Comment by hkgsherlock** [comment]
然後我沒用 proxy 在 Firefox 直連 
http://tel.dm5.com/manhua-chengweimowangdefangfa/ 
http://www.dm5.com/manhua-chengweimowangdefangfa/ 
之後是能開啟 volume list 的 ![orz](http://blog-imgs-1-origin.fc2.com/emoji/2007-08-07/145182.gif)

### tel.
```
Tracing route to idn.2fishes.cnc.ccgslb.net [58.241.16.52]
over a maximum of 30 hops:

  1     1 ms    <1 ms     1 ms  ------------.ctinets.com [----------]
  2    <1 ms    <1 ms    <1 ms  061093140045.ctinets.com [61.93.140.45]
  3     4 ms    10 ms    11 ms  014199252225.ctinets.com [14.199.252.225]
  4     *        1 ms     1 ms  014136128190.ctinets.com [14.136.128.190]
  5     7 ms     3 ms     3 ms  219.158.34.37
  6    10 ms    11 ms    11 ms  219.158.29.49
  7    10 ms    12 ms     9 ms  219.158.19.82
  8    11 ms    10 ms    10 ms  219.158.23.13
  9    34 ms    34 ms    31 ms  219.158.12.2
 10    99 ms    98 ms    99 ms  58.241.14.174
 11    37 ms    36 ms    36 ms  58.241.14.66
 12   268 ms   268 ms   268 ms  58.241.33.42
 13     *        *        *     Request timed out.
 14     *        *        *     Request timed out.
 15     *        *        *     Request timed out.
 16    37 ms    37 ms    38 ms  58.241.16.52

Trace complete.
```

### www.
```
Tracing route to www.dm5.com [95.211.197.186]
over a maximum of 30 hops:

  1     1 ms    <1 ms     1 ms  ------------.ctinets.com [----------]
  2    <1 ms    <1 ms    <1 ms  061093140173.ctinets.com [61.93.140.173]
  3     4 ms    11 ms    10 ms  014199254225.ctinets.com [14.199.254.225]
  4    78 ms     4 ms    57 ms  014136129018.ctinets.com [14.136.129.18]
  5   212 ms   212 ms   212 ms  peering.thn.lon.leaseweb.net [195.66.225.56]
  6   219 ms   214 ms   215 ms  tengige0-4-0-19.crs-evo.leaseweb.net [31.31.32.67]
  7   214 ms   213 ms   213 ms  tengige0-6-0-2.br02.ams-01.leaseweb.net [31.31.38.75]
  8   231 ms   232 ms   235 ms  tengige0-7-0-2.evo-hvc3.leaseweb.net [81.17.32.203]
  9   235 ms   235 ms   235 ms  hosted-by.raidc.com [95.211.197.186]

Trace complete.
```

By the way, JCD 是拿了哪個 host 所以解析不能？

**Comment by dxzy** [comment]
我不知道…沒有這方面的能力追蹤JCD走什麼路線

and...剛睡醒台灣時間凌晨五點，上面四個居然就可以解析了，i have no idea ,
還是純粹是dm5的問題?

>error_report_Thu Jul 23 23_42_00 CST 2015
錯誤提示：
ERROR: 網頁沒有內容（網頁下載錯誤）
錯誤原因：
網頁沒有內容（網頁下載錯誤）
錯誤發生地點：
jcomicdownloader.tools.Common.errorReport(Common.java:125)
jcomicdownloader.module.RunModule.runMainProcess(RunModule.java:80)
jcomicdownloader.module.Run.runSingleParseModule(Run.java:565)
jcomicdownloader.module.Run.run(Run.java:340)


>error_report_Thu Jul 23 23_37_25 CST 2015
錯誤提示：
ERROR: ERROR： 沒有產生D:\[漫畫]\源君物語\源君物語 第176話\
錯誤原因：
ERROR： 沒有產生D:\[漫畫]\源君物語\源君物語 第176話\
錯誤發生地點：
jcomicdownloader.tools.Common.errorReport(Common.java:125)
jcomicdownloader.module.RunModule.runSingle(RunModule.java:226)
jcomicdownloader.module.RunModule.runMainProcess(RunModule.java:70)
jcomicdownloader.module.Run.runSingleParseModule(Run.java:565)
jcomicdownloader.module.Run.run(Run.java:340)
jcomicdownloader.ComicDownGUI$7.run(ComicDownGUI.java:2443)
java.lang.Thread.run(Unknown Source)

>錯誤提示：
解析集數時發生錯誤！
錯誤原因：
String index out of range: -1
錯誤發生地點：
java.lang.String.substring(Unknown Source)
jcomicdownloader.module.ParseDM5.getVolumeTitleAndUrlOnMainPage(ParseDM5.java:1417)
jcomicdownloader.module.RunModule.runMainProcess(RunModule.java:97)
jcomicdownloader.module.Run.runSingleParseModule(Run.java:565)
jcomicdownloader.module.Run.run(Run.java:340)

**Comment by icearea** [comment]
我覺得會不是DM5做負載平衡
會把連線分到不同主機上？

**Comment by hkgsherlock** [comment]
那樣的話不同主機會出不同排版的頁面也太 囧rz

**Comment by dxzy** [comment]
昨天抓不到清單的是時候等待時間很久我、也是網路用量高峰時間，純屬猜測個人也同意上面所說，的確有可能是被分流到不能解析的地方去了，我會在不同時間多試試。orz
可能dm5真的很怕被請喝茶，所以除了ip不同導向不同站點外還搞了很多措施吧。

**Comment by hkgsherlock** [comment]
嘛～最健全的解析方法還是有的就是鳥 :poop:

**Comment by dxzy** [comment]
剛剛碰到兩站不同步，
http://www.dm5.com/manhua-yaolinvshen/  還在69話
http://tel.dm5.com/manhua-yaolinvshen/ 已經更新到70話
不過幾分鐘後就同步了

tel跟www的圖床位置一樣 (欸不怕查水錶嗎) http://manhua1025.123-159-204-166.cdndm5.com/9/8445/216253/1_4400.jpg?cid=216253&key=e2175167d0a46f5fb59329e06d0b4605 IP是china

目前還是回 tel.dm5.com 常駐省得老是被 www.dm5.com 轉回來，
對於部分限制級漫畫仍然必須要解析www.dm5，tel.dm5 是肯定不能，但明明有資源，搞不懂。

當然www.dm5 那些漫畫還是要看人品不是隨時都能解析及下載。總之真是個神奇的站。

**Comment by hkgsherlock** [comment]
>http://www.dm5.com/manhua-yaolinvshen/ 還在69話
>http://tel.dm5.com/manhua-yaolinvshen/ 已經更新到70話
>不過幾分鐘後就同步了

[我懷疑 DB 不是同一個](http://stackoverflow.com/questions/9380361/how-do-i-set-the-time-interval-for-master-slave-circular-database-replication)
然後我現在進 [tel.](http://tel.dm5.com/manhua-yaolinvshen/) 的那個，裡面現在一樣是在說

>...根据ctihk isp法律法规，我们将对...进行屏蔽...

（我們的[盲光社](http://evchk.wikia.com/wiki/%E6%98%8E%E5%85%89%E7%A4%BE)從甚麼時候開始要你天朝的害怕了？）

btw
[![好難捉摸呀.jpg](http://img.anyanother.com/data/47162.gif)](https://www.youtube.com/watch?v=BBvjuIPPFvI)
