### ISSUE TITLE
翻桌阿dmzj又改了

### ISSUE THREAD

**Issue by dxzy** [abc9070410/JComicDownloader#161]
雖然（可能）只改了網域、從manhua.dmzj.com變成dmzj1，但是JD又不能用了，自己來我半不到。
感覺也不可能有人維護了，來此為又一個過氣的神軟體上香…。

我嚴重依賴書籤跟瀏覽紀錄，看過的漫畫連結及修改的標題都一覽無遺，
隨便被改個網址就整個要重弄了…超過2000個書籤跟網只要改阿阿啊阿阿阿…1什麼1阿…。

目前有找到一個MahoMangaDownloader試用結果比起老軟體JD相對難用，無熱鍵(?!!)、速度偏慢，
有必要的朋友們可以交流下還有什麼工具可用。
 
10/14原網域回來了 真的很討厭他們無意義的改動...

**Comment by ok3672108** [comment]
作者失聯 無線改網域後也沒有更新 就一直停留舊版本 真痛苦
