### ISSUE TITLE
動漫之家手機版網址變更

### ISSUE THREAD

**Issue by dxzy** [abc9070410/JComicDownloader#17]
sorry, nothing

**Comment by dxzy** [comment]
holysh..我只是用手機點信箱網址 英文沒看懂點一下就開一篇了

btw dmzj我用都正常 也有一陣子他們沒改任何東西了
應該只是懶得爬留言版本太舊或試圖下載的漫畫是他們置入性行銷的陸產漫畫吧 那個也沒必要支援吧

**Comment by hkgsherlock** [comment]
原本我也懶得理那些人……明明上幾個留言已經講過要 report issue 就來這裡

**Comment by dxzy** [comment]
dmzj真的很熱衷於改版....

( http://manhua.dmzj.com/qiyuanzui/ ) 七原罪 因為被封 之前是到 http://mh.dmzj.com/qiyuanzui/ 下載
結果剛剛發現變成 http://m.dmzj.com/info/qiyuanzui.html 意思是dmzj覺意放棄h向不想再被查水表就對了

由於網址變了 所以目前就不能抓原手機版目錄 當然 也沒多少能抓了 值得一看的幾乎都已經被砍掉

訂閱後通知可以看到的最新一回頁面 http://manhua.dmzj.com/qiyuanzui/39396.shtml

**Comment by hkgsherlock** [comment]
那類似 8Comic 的開多一個新子 parser 這樣

**Comment by abc9070410** [comment]
5.20.150724已經可以解析新的手機版網頁

**Comment by dxzy** [comment]
thx 嘗試可用

我先前有把大量被封的漫畫加入書籤 如果有人因此感到困擾可以跟我這樣做
>因應網址格式變動 用文字編輯器開啟 bookmarkList.dat 
舉例來說 原網址是 http://mh.dmzj.com/weilian 新網址 http://m.dmzj.com/info/weilian.html
將 http://mh.dmzj.com/ 大量替換成 http://m.dmzj.com/info/
以前加入的書籤 將 /@ 替換成 .html@   將/% 替換成 .html% 儲存重開JCD 全更新了
