### ISSUE TITLE
ExHentai 下載到一半卡住

### ISSUE THREAD

**Issue by yamio** [abc9070410/JComicDownloader#18]
抱歉打擾了
問的讓我有點害羞xD
首先先感謝大大分享了這麼棒的程式，但是最近有一些問題想問看看。
之前(很久之前)下載exhentai的時候都還蠻順的，可是最近下載時就常常遇到下載到一半就會卡住的問題。
不知道這問題能解決嗎？畢竟這是少數好用又簡單的exhentai下載工具。

謝謝你喔。

＊我剛剛才發現這是公開的ＲＲＲ....(ˊ艸ˋ)

**Comment by abc9070410** [comment]
hi yamio,

1. 在v5.20.150715 之前的版本會有無限次重新嘗試下載的問題，所以請先確認你是不是已經更新到這一個版本了。
2. JComicDownloader並沒有下載timeout機制，所以如果因為某些原因導致下載進度條很慢或幾乎不會動，那還是會等到該張圖片下載完畢才會去處理下一張圖片。
3. 有時候加代理伺服器(proxy)對於EX會有幫助，如果你是中華電信用戶，可以用下面這一組:
代理伺服器位址: proxy.hinet.net , 代理伺服器: 連接阜: 80
4. 如果卡住問題還是會出現，可以翻出ErrorRecord資料夾內最新錯誤紀錄，貼上來我們可以幫忙看看。

**Comment by hkgsherlock** [comment]
可能要加一項 setting 是讓用戶設定 timeout
或者 module 內要改一下，看看能否在 timeout 時 throw exception 
因為以我記得，e(x)hentai 的網站內每頁都有一條連結是假如圖片載入失敗時去換另一個 H@H 的 server 去下載該頁圖片用的

**Comment by abc9070410** [comment]
恩好我之後研究一下怎麼加timeout機制；至於EX有備用連結這我第一次聽說@@，要再去了解一下。

**Comment by hkgsherlock** [comment]
`^https?:\/\/exhentai.org\/s\/.+$` 的話下方會有 `Click here if the image 
fails loading` 的 `<a>`
（大概 JCD 不會下載 `^https?:\/\/exhentai.org\/mpv\/.+$` 的頁面，略）

那個 `<a>` 會 call JS，但那 function `nl(a)` 也蠻廢的樣子：
```
function nl(a) {
     document.location += ((document.location + "").indexOf("?") > -1 ? 
"&" : "?") + "nl=" + a;
     return false
}
```

**Comment by abc9070410** [comment]
喔好我會看一下，順便一提，由於EX錯誤率很高，我以前有想過全部下載完畢後，再自動將下載列表的清單掃一遍，重新下載那些標記"下載錯誤"的任務。這個慢慢想怎麼做好了。

**Comment by Kennyl** [comment]
我打算打timeout改做60sec

**Comment by Kennyl** [comment]
我寫了，暫時放在feature/timeout 的branch for 測試。

**Comment by abc9070410** [comment]
恩好，那你如果測試OK，看要做成default或我再加到選項視窗裡面(當初沒想太多，所以每次要增加一個設定項目都非常繁複.....)

**Comment by Kennyl** [comment]
其實 我測不到TIMEOUT，只是改了沒影響正常下載in mac.

**Comment by yamio** [comment]
5.21版之後就一直解析失敗，可是我測試了5.20卻是可以的。

**Comment by Kennyl** [comment]
Ex 或E 都一樣？

**Comment by yamio** [comment]
我剛剛測試一下，似乎只有ex才會失敗。

**Comment by hkgsherlock** [comment]
XPanda 的話應該要有 logon session hash (cookie) 才能下載之類

**Comment by abc9070410** [comment]
我測了幾個ex沒遇到解析失敗，可以貼連結嗎? (貼"/g/"後面的部分就好)

**Comment by s0219s0219** [comment]
755698/bac0796e17/
解析失敗的

**Comment by abc9070410** [comment]
已更新在 v5.21.151220
