### ISSUE TITLE
SF: 不能下載有「RE」字眼的章節

### ISSUE THREAD

**Issue by vincentvong** [abc9070410/JComicDownloader#19]
你好，

由於東京食屍鬼RE每一期都是以RE字頭開始，所以JComicDownloader不能找到RE字頭的章節，只能找到0字頭開始的，能否改善一下呢?

**Comment by hkgsherlock** [comment]
是否所有的網站內，章節有 RE 作結尾的都失敗？

**Comment by vincentvong** [comment]
是網站內有RE字頭的都不能顯示，所以没法給下載。但數字開頭的章節郤没問題。
[image: 內置圖片 1]

2015-07-22 11:09 GMT+08:00 Puneyrf Cbba <notifications@github.com>:

> 是否所有的網站內，章節有 RE 作結尾的都失敗？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/abc9070410/JComicDownloader/issues/19#issuecomment-123549118>
> .
>



-- 


Regards,
Vincent

**Comment by hkgsherlock** [comment]
> 是網站內
哪個？還是所有都是如此？

**Comment by vincentvong** [comment]
加了網站，你的軟件會顯示可下載的章節，但它不能顯示這個網站(SF互動傳媒)的RE字頭章節。
http://comic.sfacg.com/HTML/DJSSG/

2015-07-22 12:05 GMT+08:00 Puneyrf Cbba <notifications@github.com>:

> 是網站內
> 哪個？還是所有都是如此？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/abc9070410/JComicDownloader/issues/19#issuecomment-123558090>
> .
>



-- 


Regards,
Vincent

**Comment by hkgsherlock** [comment]
`List<List<String>> getVolumeTitleAndUrlOnMainPage(String, String)` 內的 CSS 選擇器要改，稍等

**Comment by hkgsherlock** [comment]
再等我處理完 info window 那個 GitHub API 下載問題後再出 release，或你等其他人出 release 後試一下有否問題
我自己測試是 ok 的
![sshot-2015-07-22- 13-31-09](https://cloud.githubusercontent.com/assets/3526276/8818567/ec7da5b8-3075-11e5-8124-86978d98a5c6.png)

**Comment by hkgsherlock** [comment]
[JComicDownloader v5.20.150722](../releases/tag/v5.20.150722)

**Comment by vincentvong** [comment]
Thanks

Regards,
Vincent Vong

**Comment by vincentvong** [comment]
出現"解析失敗，無法讀入集數資訊!!"

2015-07-22 13:46 GMT+08:00 Puneyrf Cbba <notifications@github.com>:

> JComicDownloader v5.20.150722 <http://../releases/tag/v5.20.150722>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/abc9070410/JComicDownloader/issues/19#issuecomment-123570940>
> .
>



-- 


Regards,
Vincent

**Comment by Kennyl** [comment]
可能沒有jsoup 的jar?

**Comment by hkgsherlock** [comment]
我發覺我在 IntelliJ 用 maven panel 做完 clean + package 之後，在 
`target/` 內的 `.jar` 會用 `.jar` 外的 
`classes/jcomicdownloader/module/*.class`
但 @abc9070410 他又沒這個問題的樣子 orz

**Comment by hkgsherlock** [comment]
>可能沒有jsoup 的jar?

真是

我現在暫時先用 shade 來把 `lib/` 重包進 `.jar` 內，現在大概沒問題吧 囧rz
