### ISSUE TITLE
關閉 blogger 文章的意見回報，迫使使用者轉為在這裡回報問題/意見

### ISSUE THREAD

**Issue by hkgsherlock** [abc9070410/JComicDownloader#21]
話說到剛才還是有漏網之魚：

>匿名 已在文章 "給JComicDownloader使用者的公開信" 上留下新的意見：
>
>動漫之家下載不了
>
>張貼留言。
>
>取消訂閱此文章的意見。
>
>由 匿名 於 2015年7月24日 下午3:51 張貼在 JComicDownloader

明顯因為 blogger 的[這篇文章](http://jcomicdownloader.blogspot.com/2013/11/bug-report-8.html?ext-ref=comm-sub-email#comment-form)實在太多 comment，其他人（尤其是仍使用舊版的）還是在那裡留言，即使已經在那邊提示過要到這裡回報也是如此

想問 @abc9070410 有沒有辦法在那裡追加提示，並關閉那邊的留言（當然繼續開啟也可），引導所有人在這裡回報問題？

**Comment by abc9070410** [comment]
我找不到關閉留言的選項，先把文章下架好了。
