### ISSUE TITLE
v5.20.150724 無法解析動漫之家

### ISSUE THREAD

**Issue by shccheuk** [abc9070410/JComicDownloader#22]
我下載了JComicDownloader v5.20.150724,但JCOMICDOWNLOADER增加動漫之家某地址開始下載後,
顯示不能分柝網頁,請問是不是還要用source code,請問source code怎樣用?

**Comment by hkgsherlock** [comment]
#17

**Comment by hkgsherlock** [comment]
>src code 

不明白所指為何

見 #17 
因為 DMZJ 的網頁排版在不同的分流中的代碼差別很大，很容易就不能解析
有需要的話可以把 err log 貼進**那**邊
close

**Comment by hkgsherlock** [comment]
看錯了以為 DM5… orz
有沒有 error log 以及你是拆解哪頁的 URL？

**Comment by shccheuk** [comment]
下載這個漫畫
http://manhua.dmzj.com/mfkgxdldsjxzp/


錯誤提示：
ERROR: 網頁沒有內容（網頁下載錯誤）
錯誤原因：
網頁沒有內容（網頁下載錯誤）

錯誤發生地點：
jcomicdownloader.tools.Common.errorReport(Common.java:125)
jcomicdownloader.module.RunModule.runMainProcess(RunModule.java:80) 

jcomicdownloader.module.Run.runSingleParseModule(Run.java:565)
jcomicdownloader.module.Run.run(Run.java:315)

**Comment by dxzy** [comment]
呃......我可以下載.......
\魔法科高校的劣等生：九校戰篇\第022話

**Comment by hkgsherlock** [comment]
\實在是太神奇喇/
再看

**Comment by hkgsherlock** [comment]
can parse but cannot restart on 403 ( => #59 ), close
