### ISSUE TITLE
v5.20.150724 無法解析dm5 部份漫畫，但v5.20.150703可以

### ISSUE THREAD

**Issue by lturtle22** [abc9070410/JComicDownloader#25]
v5.20.150724 無法解析dm5 部份漫畫，但v5.20.150703可以解析並下載。
例如:
http://tel.dm5.com/manhua-kissxdeath/

**Comment by dxzy** [comment]
不過網址改成 www.dm5.com 可以 lol

**Comment by Kennyl** [comment]
我用www的error 是
此為限制漫畫，重新下載網頁

**Comment by Kennyl** [comment]
限制級如果用了proxy 或vpn不行、那就暫無解決方法

**Comment by dxzy** [comment]
實際上我現在也開始在用0703下載DM5了
在新版碰到不能解析限制級的時候(解析失敗要換時間重試 下載同解析)
0703版全時段都能解跟下載(還沒碰到失敗過) 完全搞不懂理由

**Comment by hkgsherlock** [comment]
大概要 compare / blame 一下發生了什麼事

ps 我現在還是在忙其他東西 orz

**Comment by dxzy** [comment]
目前我只能假設有種可能是：
ip沒被dm5封「限制級」的使用者可以用0703，
被封的用0724可以繞過(？)，
如果是這樣就很難一網打盡。

大丈夫萌大奶，還能抓就沒問題😗

**Comment by hkgsherlock** [comment]
要兩個版本的 parser ，然後 settings file + dialog
我的媽呀

**Comment by Kennyl** [comment]
但兩個版本我都下載不倒。

2015-08-06 18:55 GMT+08:00 Puneyrf Cbba <notifications@github.com>:

> 要兩個版本的 parser ，然後 settings file + dialog
> 我的媽呀

**Comment by dxzy** [comment]
如果直接給網址、瀏覽器可以繞過去嗎？
http://tel.dm5.com/manhua-kissxdeath/ or http://www.dm5.com/manhua-kissxdeath/
http://tel.dm5.com/m216681/ ←連這個也會屏蔽嗎 會的話感覺DMZJ太小兒科了…
(屏蔽的太隨便難怪怕的連蟲奉行沒露的都自己弄聖光上去…)
如果瀏覽器都看不到圖，JCD要抓到也有難度吧…(?)

圖片網址還沒用
http://manhua1025.101-69-161-204.cdndm5.com/17/16431/216681/1_7904.jpg?cid=216681&key=356ad1add71a6c2efce39dce61d95d71
＂cid=.......＂每次都會變換，Firefox的RefControl都無用武之地了...

**Comment by Kennyl** [comment]
https://github.com/abc9070410/JComicDownloader/releases/download/v5.21.150807/JComicDownloader-v5.21-SNAPSHOT.jar
有時間請幫手用這version測試。

**Comment by dxzy** [comment]
測試結果：0807可以下載 (同時間0724不能下載 www.dm5.com 、0703可以下載) 台灣中華電信

BUG：
如果排序，下載清單會錯亂，例如勾選的是源君物語170~177，排序，下載時會變成2~8+177話。

另，這次輸出的目錄是簡體字 (舊:源君物語 新:源君物语)

**Comment by Kennyl** [comment]
更正了小許

**Comment by dxzy** [comment]
更正號排序BUG已修正

關於繁簡問題 個人是都可以配合只是有存漫畫的習慣要一次重改過這OK
但實際上有別的問題 我測試了一下抓DMZJ
結果JCD沒有將以下載(建立過的集數子資料夾觀測到)
我猜兩種可能：
１、因為資料夾名稱多為第__話 在繁簡的判別上有問題
２、改了某種東西 跟繁簡無關 看得出來分析清單的字體都不一樣了 放圖對照
![2015-08-07 14 31 06](https://cloud.githubusercontent.com/assets/13295999/9130014/29e7bc7a-3d11-11e5-89b6-9714d8adc624.png)

**Comment by Kennyl** [comment]
因為重寫，不知道以前的Title是bug 還是正常

**Comment by Kennyl** [comment]
dmzj 還是dm5, 我剛剛改的是dm5 .

2我改正了

**Comment by dxzy** [comment]
我只是用DMZJ測試上圖左邊那個灰色效果是否正常(結果一樣不正常) 是不是只有DM5這樣

新版本 (released this 17 minutes ago) 測試後相同 已下載章節不會反灰(圖左)
同上圖右 分析時集數顯示的都是正體中文 但看上面漫畫標題是簡體中文

然後測試排序 發現DM5正常了不會錯亂 但DMZJ卻錯亂了XD (啥 lol)

**Comment by shccheuk** [comment]
下載V5.21後打開,發覺顯示JSOUP-1.8.2.JAR下載完畢,請注意,程式即將重新啟動,
但重新啟動後一直重新啟動後,沒完沒了

**Comment by Kennyl** [comment]
lib folder 有沒有JSOUP-1.8.2.JAR？

**Comment by shccheuk** [comment]
用V5.21full後沒有再重新啟動程式了,
但和V5.20一樣(我自己個別情況吧),還是分析不了網頁,DM5和動漫之家也一樣
錯誤提示：
ERROR: 網頁沒有內容（網頁下載錯誤）
錯誤原因：
網頁沒有內容（網頁下載錯誤）

錯誤發生地點：
jcomicdownloader.tools.Common.errorReport(Common.java:127)
jcomicdownloader.module.RunModule.runMainProcess(RunModule.java:80)
jcomicdownloader.module.Run.runSingleParseModule(Run.java:169)
jcomicdownloader.module.Run.run(Run.java:153)

**Comment by Kennyl** [comment]
我想是你的OS /網路問題。
