### ISSUE TITLE
無法下載 99Comic

### ISSUE THREAD

**Issue by b000408** [abc9070410/JComicDownloader#28]
http://www.99comic.com/ 網站在試圖下載時可以分析網站 然而無法下載 無法生成檔案資料夾與儲存檔案

**Comment by hkgsherlock** [comment]
版本？

**Comment by b000408** [comment]
Latest snapshot

Puneyrf Cbba <notifications@github.com> 於 2015年8月8日 星期六寫道：

**Comment by Kennyl** [comment]
應該前的SNAPSHOT已改了
