### ISSUE TITLE
5.21.150812 , 書籤無法顯示己下載好的集數

### ISSUE THREAD

**Issue by ballcat** [abc9070410/JComicDownloader#29]
我是下 8comic 的
有的己下載好的漫畫 , 可是在點選 "加入下載任務" 時 , 無法將己下載的部份反灰

**Comment by Kennyl** [comment]
可否給例子或截圖？

**Comment by dxzy** [comment]
https://cloud.githubusercontent.com/assets/13295999/9130014/29e7bc7a-3d11-11e5-89b6-9714d8adc624.png

**Comment by Kennyl** [comment]
如果係dm5 ,繁簡問題已改，如果 標題名稱 因為板本有異 要出現沒有反灰，我暫不會改，想不倒辦法。
如果 a site 下載完 b site 再下載，也不保證會反灰。

**Comment by dxzy** [comment]
很擔心有語言差異所以無法正確表達 lol
關於V5.21.150812 標題名稱應該都能接受、繁簡已修正(非常感謝如此迅速)，
不過反灰是一直延續下來都有的功能所以使用者可能很難習慣失去它。

跟dm5或dmzj或8comic無關，我猜測(I guess)這跟GUI有關，因為V5.21重寫很多東西以至於不再具有或BUG以致反灰的功能喪失。最後附圖，好像沒必要了就是。
![2015-08-15 14 09 06](https://cloud.githubusercontent.com/assets/13295999/9287728/800deb46-4357-11e5-862e-2dab268887fa.png)

**Comment by Kennyl** [comment]
我會研究，是不是有標點符號的漫有問題，即重新下載那些檔案會出現在哪裡，會覆蓋？

**Comment by dxzy** [comment]
nonononon 就很簡單的一件事 不會變灰色 除此之外都正常

**Comment by Kennyl** [comment]
v5.20.150724 也是正常？ 那麼我要一些時間找是什麼問題。

**Comment by Kennyl** [comment]
在我的電腦上 v5.20.150724 到snapshot 上也是反灰。有沒有其他Collaborator試過？

**Comment by Kennyl** [comment]
請試一試新板，我懷疑是windows 7才出現的bug.
http://stackoverflow.com/questions/919918/file-exists-returns-false-when-file-exists

**Comment by dxzy** [comment]
呃 0817我這邊試了不少本漫畫 沒變化

**Comment by Kennyl** [comment]
毫無頭緒，如果刪了任務再加入呢？

**Comment by dxzy** [comment]
不行 XD (拍拍)

**Comment by Kennyl** [comment]
投降

**Comment by abc9070410** [comment]
5.21.150822暫時修復了，但這樣改會讓Mac OS X的選擇視窗有灰邊，之後再慢慢找兩全之道吧。

![temp12](https://cloud.githubusercontent.com/assets/2183861/9423171/dce1c722-48eb-11e5-9750-d8e93c9ead56.PNG)

**Comment by dxzy** [comment]
晚了一天才有空回報 試過有效
