### ISSUE TITLE
Not available at mangafox.me

### ISSUE THREAD

**Issue by prenfic** [abc9070410/JComicDownloader#31]
Tested on, http://mangafox.me/manga/one_piece/
Environment:
Win10 latest update+Java 8.0.310

Once I click on, download,
show me the list of mangas,
but got no response after click of download button.

**Comment by abc9070410** [comment]
This issue is fixed. 
You could try the version 5.21.150822.

**Comment by prenfic** [comment]
@abc9070410 dude, i just saw it,
thank you
