### ISSUE TITLE
v5.21.150830 GUI (?) 錯誤

### ISSUE THREAD

**Issue by dxzy** [abc9070410/JComicDownloader#34]
![2015-09-02 11 21 44](https://cloud.githubusercontent.com/assets/13295999/9622394/0b4af238-5165-11e5-8401-aad217cbac28.png)

如圖除了 Re:monster以外都正常顯示 http://tel.dm5.com/manhua-re-monster/
其他都是DMZJ的項目，dm5只有另一個源君物語但顯示正常。

滑鼠劃過去會顯示，但中央仍然是全黑的。摸黑勾選是可以勾，但不能下載。
(用舊版能正常抓所以無所謂…)

之後使用發現似乎在分析那種集數太多的漫畫時右邊的滾動軸會消失 XD
最低只知道網球優等生149集右邊就不見了。

**Comment by Kennyl** [comment]
如果更改UI , 如Jtattoo有沒有改善？

**Comment by dxzy** [comment]
發現把視窗拉長右側滾動軸就會顯示了，好像只要因為項目多而縮小到一定程度時，
表示滾動位置的 口 就會消失，拉長視窗就相對放大 口 於是就出現了。

另外 Re:monster 在想會不會又是名稱錯誤的問題沒吧『:』處理好導致無法建立資料夾以致全黑?
之前版本資料夾名稱是Re_Monster，而新版似乎出現同樣問題 ↓

錯誤提示：
ERROR: ERROR： 沒有產生D:\[漫畫]\Re:Monster\第017話\
錯誤原因：
ERROR： 沒有產生D:\[漫畫]\Re:Monster\第017話\

錯誤發生地點：
jcomicdownloader.tools.Common.errorReport(Common.java:133)
jcomicdownloader.module.RunModule.runSingle(RunModule.java:225)
jcomicdownloader.module.RunModule.runMainProcess(RunModule.java:70)
jcomicdownloader.module.Run.runSingleParseModule(Run.java:169)
jcomicdownloader.module.Run.run(Run.java:153)
jcomicdownloader.ComicDownGUI$7.run(ComicDownGUI.java:2486)
java.lang.Thread.run(Unknown Source)

**Comment by Kennyl** [comment]
Title 名已更正，等下一release 吧。

**Comment by dxzy** [comment]
我用是不行

錯誤提示：
無法正確下載http://manhua1025.123-159-204-166.cdndm5.com/17/16644/219687/18_9111.png?cid=219687&key=a4e4fbb21c35a792e510a2f1fe787c76！

錯誤原因：
D:\[漫畫]\Re:Monster\第017話\018.png (檔案名稱、目錄名稱或磁碟區標籤語法錯誤。)

錯誤發生地點：
java.io.FileOutputStream.open0(Native Method)
java.io.FileOutputStream.open(Unknown Source)
java.io.FileOutputStream.<init>(Unknown Source)
java.io.FileOutputStream.<init>(Unknown Source)
jcomicdownloader.tools.Common.simpleDownloadFile(Common.java:2771)
jcomicdownloader.module.ParseOnlineComicSite.singlePageDownload(ParseOnlineComicSite.java:310)
jcomicdownloader.module.ParseOnlineComicSite.singlePageDownloadUsingSimple(ParseOnlineComicSite.java:249)
jcomicdownloader.module.ParseDM5.parseComicURL(ParseDM5.java:859)
jcomicdownloader.module.RunModule.runSingle(RunModule.java:173)
jcomicdownloader.module.RunModule.runMainProcess(RunModule.java:70)
jcomicdownloader.module.Run.runSingleParseModule(Run.java:169)
jcomicdownloader.module.Run.run(Run.java:153)
jcomicdownloader.ComicDownGUI$7.run(ComicDownGUI.java:2486)
java.lang.Thread.run(Unknown Source)

**Comment by dxzy** [comment]
另外，不知道是不是個案，好像最近版本下載有時會缺頁但並沒有像以往一樣顯示下載錯誤而是下載完畢。
--
錯誤提示：
ERROR: 錯誤回傳碼(responseCode): 404 : http://manhua1025.123-159-204-166.cdndm5.com/16/15173/220082/D.png?cid=220082&key=be78536cdfeb9388498587153ad50e97
錯誤原因：
錯誤回傳碼(responseCode): 404 : http://manhua1025.123-159-204-166.cdndm5.com/16/15173/220082/D.png?cid=220082&key=be78536cdfeb9388498587153ad50e97

錯誤發生地點：
jcomicdownloader.tools.Common.errorReport(Common.java:133)
jcomicdownloader.tools.Common.simpleDownloadFile(Common.java:2762)
jcomicdownloader.module.ParseOnlineComicSite.singlePageDownload(ParseOnlineComicSite.java:310)
jcomicdownloader.module.ParseOnlineComicSite.singlePageDownloadUsingSimple(ParseOnlineComicSite.java:249)
jcomicdownloader.module.ParseDM5.parseComicURL(ParseDM5.java:859)
jcomicdownloader.module.RunModule.runSingle(RunModule.java:173)
jcomicdownloader.module.RunModule.runMainProcess(RunModule.java:70)
jcomicdownloader.module.Run.runSingleParseModule(Run.java:169)
jcomicdownloader.module.Run.run(Run.java:153)
jcomicdownloader.ComicDownGUI$7.run(ComicDownGUI.java:2486)
java.lang.Thread.run(Unknown Source)

**Comment by dxzy** [comment]
v521 0907
dm5好像沒缺頁了 目錄名稱也正確(回復Re_Monster) 會繼續觀察 多謝 多謝

**Comment by Kennyl** [comment]
缺頁只是機
