### ISSUE TITLE
DM5 漫画页面丢失

### ISSUE THREAD

**Issue by whitehumorous** [abc9070410/JComicDownloader#37]
刚用了最新版本下载，发现漫画有部分页面会没下载到，重新下载也一样。
我的漫画都是DM5的。

**Comment by Kennyl** [comment]
試一試這，https://github.com/abc9070410/JComicDownloader/releases/tag/v5.21.150907 
有問題請再報告。

**Comment by whitehumorous** [comment]
好的，感谢您的无私。

**Comment by whitehumorous** [comment]
同样的问题还是存在，总会有几页没下载到。

**Comment by dxzy** [comment]
我先前也會但0907之後沒再發生，你是抓哪本掉頁的…

**Comment by whitehumorous** [comment]
我把旧的dat file删除掉问题就没了，谢谢！
