### ISSUE TITLE
您好，感謝您的修復！不過發現一個問題 (dependencies: genson)

### ISSUE THREAD

**Issue by linnet6** [abc9070410/JComicDownloader#38]
太感謝了！您簡直比神還靈驗！下載方面完全沒有問題了！謝謝您！
但其他方面卻發現一個小問題，
我發現每當我點選"資訊"選項時就會跳出警告視窗，
寫著:"genson-1.3.jar下載完畢，請注意，程式即將重新啟動!"
按下確定之後程式便重新啟動了，我還試著重啟自己的電腦，不過並沒有幫助，
不曉得是我的電腦還是程式的問題，還是得麻煩您了！
最後還是謝謝您！既然您不需要贊助，我會在拜拜的時候順便請佛祖保佑您身體健康！謝謝！

**Comment by Kennyl** [comment]
你有沒有有看見genson-1.3.jar 下載到你的lib內？
因為應該會從這https://github.com/abc9070410/JComicDownloader/tree/gh-pages下載

**Comment by Kennyl** [comment]
https://github.com/abc9070410/JComicDownloader/releases/tag/v5.21.150907
你可以試一下xxxx-full.jar看有沒有改善。

**Comment by linnet6** [comment]
確實沒在lib看到genson-1.3.jar 
試了full.jar就完全沒問題了！非常謝謝你！感謝！

**Comment by abc9070410** [comment]
不是FULL版的JComicDownloader在開啟資訊視窗的時候會需要下載genson-1.3.jar，若下載失敗或無法放在適當資料夾，則資訊視窗會開啟失敗。

新版本已經加入提示資訊，且當找不到genson-1.3.jar，不會嘗試開啟資訊視窗。

所以為了避免沒有寫入權限而載入genson-1.3.jar失敗，建議JComicDownloader不要放在系統資料夾，放在"下載"、"文件"這些使用者資料夾會比較好。

**Comment by linnet6** [comment]
了解，謝謝您!
