### ISSUE TITLE
小部分卷/话数无法下载

### ISSUE THREAD

**Issue by whitehumorous** [abc9070410/JComicDownloader#39]
以下卷/话数无法下载，线上可以看。

http://www.dm5.com/manhua-tianshengmiaoshou/
第35，36卷

http://www.dm5.com/manhua-wangqiuwangzi/
366~368话

http://www.dm5.com/manhua-huoyingrenzhe-naruto/
379，380话

http://www.dm5.com/manhua-fengyunquanji/
509~511话

ErrorRecord

ERROR： 沒有產生C:\JComic Downloader\down\天生妙手\第035卷\jcomicdownloader.tools.Common.errorReport(Common.java:133)
jcomicdownloader.module.RunModule.runSingle(RunModule.java:225)
jcomicdownloader.module.RunModule.runMainProcess(RunModule.java:70)
jcomicdownloader.module.Run.runSingleParseModule(Run.java:169)
jcomicdownloader.module.Run.run(Run.java:153)
jcomicdownloader.ComicDownGUI$7.run(ComicDownGUI.java:2486)
java.lang.Thread.run(Unknown Source)

**Comment by dxzy** [comment]
試過http://www.dm5.com/manhua-fengyunquanji/509~511话的確不行

**Comment by Kennyl** [comment]
y.jpg 好像是盗連判定。
