### ISSUE TITLE
有關於書籤的移動

### ISSUE THREAD

**Issue by ballcat** [abc9070410/JComicDownloader#40]
請問一下
像有的漫畫己完結 , 所以個人會把它移動到最下方

可是最近好像無法移動 , 移了然後在下次再進程式之時 , 就會恢復原來的位置

這個是我的操作方式不對嗎??

**Comment by abc9070410** [comment]
我試了移動書籤的位置後關閉後重啟程式，書籤還是在移動後的位置。
你移動後關閉再開啟程式來看看
