### ISSUE TITLE
請問是否可以幫忙看一下，我的不能下載動漫之家，謝謝

### ISSUE THREAD

**Issue by elisaaa** [abc9070410/JComicDownloader#47]
您好:
今天下載發現會解析失敗，顯示任務完成但是沒有任何檔案，是那出了狀況，
能否請幫忙呢，謝謝
http://manhua.dmzj.com/
錯誤提示：
在解析下載網址或下載過程中發生錯誤！

錯誤原因：
String index out of range: -1

錯誤發生地點：
java.lang.String.substring(Unknown Source)
jcomicdownloader.module.Parse178.parseComicURL(Parse178.java:1101)
jcomicdownloader.module.RunModule.runSingle(RunModule.java:173)
jcomicdownloader.module.RunModule.runMainProcess(RunModule.java:70)
jcomicdownloader.module.Run.runSingleParseModule(Run.java:169)
jcomicdownloader.module.Run.run(Run.java:153)
jcomicdownloader.ComicDownGUI$7.run(ComicDownGUI.java:2486)
java.lang.Thread.run(Unknown Source)

**Comment by Kennyl** [comment]
試不倒，你可能一時連不倒網站。
