### ISSUE TITLE
Mac環境下無法完整下載

### ISSUE THREAD

**Issue by None114055** [abc9070410/JComicDownloader#48]
我下載的是DM5的UQ HOLDER!

第一話有80頁但下載完頁數不完整

是否和檢查機制不夠可以增加檢查機制嗎？或有其他解決方法？

可以增加一整個資料夾壓縮並命名cbz的選項嗎？

  例如我下載UQ HOLDER!整個UQ HOLDER!漫畫壓縮成一個cbz檔

![2015-11-02 3 58 00](https://cloud.githubusercontent.com/assets/15607057/10876828/4488a89c-817b-11e5-8d86-a605de21c2bf.png)

![2015-11-02 3 58 09](https://cloud.githubusercontent.com/assets/15607057/10876829/44c8f50a-817b-11e5-8a01-8417208d5d1e.png)

![2015-11-02 3 58 15](https://cloud.githubusercontent.com/assets/15607057/10876830/44cae25c-817b-11e5-8534-e08a930521b7.png)

**Comment by Kennyl** [comment]
你可以將重試選項調做二次以上。zip 和cbz 分別不大，你可以自行改做cbz試試看。

**Comment by abc9070410** [comment]
抱歉沒辦法一整個壓縮成cbz，是因為java原生的zip library對於Unicode支援有問題，如果把整部作品壓縮成一個檔案，勢必要把每一集的資料夾也壓縮進去，那麼資料夾的名稱會變成亂碼而無法讀取。

至於下載不完整的問題，可以利用原本的重新下載機制，如圖:
![image](https://cloud.githubusercontent.com/assets/2183861/13026229/28e0178e-d25b-11e5-878e-e1ac15cedcd3.png)

或使用新版本，新版本在整集下載完會檢查有沒有下載不完整的圖片，如果有發現，會進行重新下載。
https://github.com/abc9070410/JComicDownloader/releases/tag/v5.21.160213
