### ISSUE TITLE
生成的Zip文件无法使用MangaMeeya打开。

### ISSUE THREAD

**Issue by xJogger** [abc9070410/JComicDownloader#49]
显示“读取失败”。
JComicDownloader 版本 ：5.21.150920
还需要什么信息么，我尽量提供。

**Comment by hkgsherlock** [comment]
not found such issue from MangaMeeyaCE 2.4beta
tested using manga Gintama 565 d/led from jcomic 5.21.150920

Maybe upload your zip, and providing version of your MangaMeeya. I'll have a try once I'm a bit free.

**Comment by xJogger** [comment]
My MangaMeeya version is 7.4.
I downloaded Gintama 565 from kukudm using jcomic 5.21.150920 and found MangaMeeya still can't open the zip file.
I post the URL of my MangaMeeya and the zip of Gintama 565 here:
http://pan.baidu.com/s/1mg92xsO   PW:8pz5
What's more, my Java version is 8.0.600.27.

**Comment by hkgsherlock** [comment]
(其實用中文沒問題，只是我回覆的那部電腦沒法打中文

我大概把原版跟 CE 版混淆了
試過了，似乎是 ZIP 的 blob 內容排序導致 MangaMeeya 讀取失敗
要再看是否只是 `java.util.zip` 還是其實是本身寫錯，etc

暫時沒空，看其他人是否有空再幫忙 fix

**Comment by xJogger** [comment]
嗯，问题反馈到了就好。
您看您有时间再修复。

**Comment by Kennyl** [comment]
會不會是中文亂碼，因為ZIP不太好支援。

**Comment by hkgsherlock** [comment]
但是我試過 rezip 過 JCD 壓出來的檔案之後又沒事 orz

**Comment by abc9070410** [comment]
JComicDownloader產生壓縮檔裡面不會有資料夾，而且檔名都只有流水號，所以應該不會是中文支援的問題(然而實際上ZipOutputStream對於中文支援真的有問題.....)

剛剛試了很久，發現可能是MangaMeeya會檢查zip檔裡的CRC資訊，如果沒有就讀取失敗。
因為我嘗試在創建zip檔的時候加入CRC資訊，就能順利讀取了。

xJogger你可以試試看下面這個版本:
http://pan.baidu.com/s/1nt6IHrb

幫忙測試看看這個版本寫出zip壓縮檔有沒有比較慢，因為這樣改需要算出每個圖檔的CRC再寫進去。
如果沒有明顯差異，之後再更新到新的版本上面~

**Comment by Kennyl** [comment]
http://www.java-examples.com/create-zip-file-crc32-checksum-example

這個寫法較簡潔。

**Comment by xJogger** [comment]
我试了下 abc9070410 加入CRC校验值的版本，生成的Zip用MangaMeeya可以正常打开。
我测试了一话页数比较少的（小埋第132话，9页），没有感觉到压缩的时间，改天我再测试大一点的。

**Comment by abc9070410** [comment]
to Kennyl:
恩簡潔很多，但那個範例只支援單一檔案，我不太會改成支援整個資料夾的，所以不確定實際效率是不是會比較好

to xJogger:
OK可以開就好，之後有空再測大檔吧。

**Comment by xJogger** [comment]
to abc9070410
我今天分别用0920版和1129版下载了(星河万山灵草纸)[http://m.dmzj.com/info/xhwslcz.html]的第一卷，共92页、34.7兆，两个版本生成压缩文件所花的时间都很短，大约不到一秒。
我是将压缩文件的生成时间减去最后一张图片的生成时间，从而得到生成压缩文件的时间，这样计算应该没有问题吧。

**Comment by abc9070410** [comment]
喔感謝那應該沒問題了，之後版本會把這個加進去。

**Comment by Kennyl** [comment]
我的PR有bug 稍後会改
2015年12月2日 下午11:10 於 "surveyorK" <notifications@github.com> 寫道：

**Comment by Kennyl** [comment]
還是用s大的commit ,我的pR想法行不通
2015年12月3日 上午12:37 於 "Kenny Liu" <me@kennyforge.com> 寫道：

**Comment by abc9070410** [comment]
已更新在 v5.21.151220
