### ISSUE TITLE
經常發生一話漫畫有幾頁下載失敗的情況

### ISSUE THREAD

**Issue by yyq1983** [abc9070410/JComicDownloader#51]
之前下載20幾話的漫畫，幾乎每一話都有下載到空白頁，而網站上那些空白頁其實都是完好的，只得刪除文件重下，能不能每下完一話做一個顯示下載失敗文件的提示，讓用戶能選擇直接重新下載失敗的文件，

**Comment by abc9070410** [comment]
你可以利用原本的重新下載機制，如圖:
![image](https://cloud.githubusercontent.com/assets/2183861/13026229/28e0178e-d25b-11e5-878e-e1ac15cedcd3.png)

或使用新版本，新版本在整集下載完會檢查有沒有下載不完整的圖片，如果有發現，會進行重新下載。
https://github.com/abc9070410/JComicDownloader/releases/tag/v5.21.160213
