### ISSUE TITLE
[Wiki] IntelliJ 建置最後一個步驟 "manifest.mf" 檔案在何處？

### ISSUE THREAD

**Issue by mxgit1090** [abc9070410/JComicDownloader#53]
試著下載後試著用 IntelliJ 建置
最後一個步驟要使用 manifest.mf 卻找不到
相關資訊僅在 pom.xml 檔中找到

請問要不要將檔案放回去？
還是說修改一下 Wiki ?

謝謝！

**Comment by hkgsherlock** [comment]
你有沒有安裝 maven，然後用 maven build project？

**Comment by mxgit1090** [comment]
是說以下的指令嗎：
```bash
mvn clear install
```
如果是的話，有，但沒有看到檔案。

**Comment by Kennyl** [comment]
暫時不要用IDE，在 console 的project folder，打 mvn clean install.

**Comment by Kennyl** [comment]
另本人用run configuration 代替artifact
<img width="603" alt="screen shot 2016-08-24 at 4 02 47 pm" src="https://cloud.githubusercontent.com/assets/1933134/17922966/51e22cca-6a14-11e6-80f5-5a17338ba899.png">
