### ISSUE TITLE
百度貼吧圖片無法下載

### ISSUE THREAD

**Issue by a1533062** [abc9070410/JComicDownloader#56]
我試著用jc去下載http://tieba.baidu.com/p/4311595337這個帖子的圖片
但一直處於進行分析無法下載
想請問是為什麼??
懇請解答

**Comment by abc9070410** [comment]
已經修復這個問題，請下載下方的版本，謝謝。

https://github.com/abc9070410/JComicDownloader/releases/tag/v5.21.160213
