### ISSUE TITLE
有關substance介面的缺點或錯誤

### ISSUE THREAD

**Issue by cxzxudhs** [abc9070410/JComicDownloader#57]
http://imgur.com/KpwnRxh
發現使用substance系列的介面時按鈕標題會消失。

**Comment by cxzxudhs** [comment]
補述：使用環境是Win7。

**Comment by abc9070410** [comment]
剛試了一下，看起來只要視窗放大就會顯示完整按鈕文字了。

文字放不下的時候只有點點點，如下圖:
![image](https://cloud.githubusercontent.com/assets/2183861/13030654/e90705f4-d2ec-11e5-97cd-d2d974e62fb1.png)

拉寬視窗後就能顯示了，如下圖:
![image](https://cloud.githubusercontent.com/assets/2183861/13030658/0a54e5fa-d2ed-11e5-994e-9bd2c14cc15a.png)

**Comment by cxzxudhs** [comment]
解決了，謝謝。
