### ISSUE TITLE
comicvip改版成comicbus了

### ISSUE THREAD

**Issue by Clarkliu0919** [abc9070410/JComicDownloader#58]
新漫畫已經無法下載，請撥空改版

**Comment by hkgsherlock** [comment]
連 `cview` 那個 function 也改了
不過反正只有那些地方而我又要下 WORKING! 就隨便改了一下

**Comment by Clarkliu0919** [comment]
抱歉 還是不行
--
錯誤提示：
無法正確下載http://img55.8comic.com/8/10632/2824/001_627.jpg！

錯誤原因：
img55.8comic.com

錯誤發生地點：
sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
java.net.HttpURLConnection.getResponseCode(Unknown Source)
jcomicdownloader.tools.Common.downloadFile(Common.java:645)
jcomicdownloader.tools.Common.downloadFile(Common.java:795)
jcomicdownloader.tools.Common.downloadManyFile(Common.java:289)
jcomicdownloader.module.RunModule.runSingle(RunModule.java:199)
jcomicdownloader.module.RunModule.runMainProcess(RunModule.java:70)
jcomicdownloader.module.Run.runSingleParseModule(Run.java:565)
jcomicdownloader.module.Run.run(Run.java:230)
jcomicdownloader.ComicDownGUI$7.run(ComicDownGUI.java:2443)
java.lang.Thread.run(Unknown Source)

**Comment by hkgsherlock** [comment]
請報上當時你下載的漫畫的網址以及正在下載的集、頁數

**Comment by Clarkliu0919** [comment]
http://www.comicbus.com/html/10238.html
29集不行

**Comment by nagitoraneko** [comment]
http://www.comicbus.com/html/10166.html
http://www.comicbus.com/html/11403.html
http://www.comicbus.com/html/13363.html
http://www.comicbus.com/html/8475.html
http://www.comicbus.com/html/8900.html
http://www.comicbus.com/html/8702.html
以上這些是目前也已經發現會出現下載錯誤狀況的 全部都一話也抓不到

**Comment by dong1121** [comment]
目前在下載「西游」(http://www.comicbus.com/html/13505.html)
會抓到「春秋戰雄」的頁面(http://www.comicbus.com/html/7000.html)
下載器不會出現錯誤訊息喔~
再麻煩大大確認一下~謝謝！

**Comment by abc9070410** [comment]
應該已經修復，請用下面的版本:
https://github.com/abc9070410/JComicDownloader/releases/tag/v5.21.160610
