### ISSUE TITLE
百度貼吧下載時不會換頁

### ISSUE THREAD

**Issue by night0081** [abc9070410/JComicDownloader#60]
下載貼吧的圖片時
第一頁圖片全下載後顯示下載成功, 但不會跳換至下一頁下載

**Comment by abc9070410** [comment]
hi可以提供有問題的貼吧連結嗎?

我嘗試http://tieba.baidu.com/p/4530493052，可以下載後面頁數的圖片

**Comment by wxc13240** [comment]
這一篇文無法跨頁下載

http://tieba.baidu.com/p/4564370619?see_lz=1

**Comment by abc9070410** [comment]
已經修復貼吧跨頁下載問題，請用下方版本:

https://github.com/abc9070410/JComicDownloader/releases/tag/v5.21.160928
