### ISSUE TITLE
SF在线漫画下載失敗

### ISSUE THREAD

**Issue by potami** [abc9070410/JComicDownloader#61]
在SF在线漫画(http://comic.sfacg.com/)下載時,只能抓到3k的圖檔

**Comment by abc9070410** [comment]
已經修復，請用下面的版本:
https://github.com/abc9070410/JComicDownloader/releases/tag/v5.21.160610

**Comment by potami** [comment]
使用新版會出現下面的訊息
![image](https://cloud.githubusercontent.com/assets/16659934/15988564/2a9251ec-3088-11e6-9e94-beb9b7f50bcc.png)
