### ISSUE TITLE
您好 , 集數下載錯誤

### ISSUE THREAD

**Issue by ballcat** [abc9070410/JComicDownloader#62]
您好
集數下載錯誤 , 漫畫 : 舌尖上的地下城
http://www.comicbus.com/html/11403.html

第24集會變成別的漫畫下載回來 , 而直接web看是正確的

**Comment by dxzy** [comment]
http://pan.baidu.com/share/home?uk=3057094636#category/type=0
這我喜歡下載原版的

**Comment by abc9070410** [comment]
已經修復，請用下面的版本:
https://github.com/abc9070410/JComicDownloader/releases/tag/v5.21.160610

**Comment by dxzy** [comment]
感激不盡
