### ISSUE TITLE
下载不了，一直在报错，原因不明

### ISSUE THREAD

**Issue by deviljz** [abc9070410/JComicDownloader#63]
错误提示：
ERROR: ERROR： 没有产生D:\漫画下载\半夜的X仪式\第001话\
错误原因：
ERROR： 没有产生D:\漫画下载\半夜的X仪式\第001话\

错误发生地点：
jcomicdownloader.tools.Common.errorReport(Common.java:165)
jcomicdownloader.module.RunModule.runSingle(RunModule.java:202)
jcomicdownloader.module.RunModule.runMainProcess(RunModule.java:70)
jcomicdownloader.module.Run.runSingleParseModule(Run.java:169)
jcomicdownloader.module.Run.run(Run.java:153)
jcomicdownloader.ComicDownGUI$7.run(ComicDownGUI.java:2486)
java.lang.Thread.run(Unknown Source)

看起来像是无法创建目录？但就算我手动创建了目录也还是不行

**Comment by deviljz** [comment]
http://www.dm5.com/manhua-banyede-x-yishi/
网址

**Comment by deviljz** [comment]
补充下，试了个dmzj的可以下，大概是dm5防盗链之类的问题

**Comment by dxzy** [comment]
我可以 你連上網站可以看嗎 還是會被擋?

**Comment by deviljz** [comment]
我上网站看到的是
半夜的X仪式漫画 中有部份章节可能含有暴力、血腥、色情或不当的语言等内容，根据中国法律法规，我们将对 半夜的X仪式漫画 进行屏蔽。如有您疑问请联系我们反馈问题，给您带来不便，敬请谅解！

所以才试着用jComicDownloader下

**Comment by deviljz** [comment]
可能他们是判断ip的？

**Comment by dxzy** [comment]
對dm5是用IP判斷的 同樣IP下這程式一樣會被擋
