### ISSUE TITLE
capture the same picture on http://comic.ck101.com

### ISSUE THREAD

**Issue by SY9226** [abc9070410/JComicDownloader#66]
Capture the same picture

**Comment by SY9226** [comment]
錯誤提示：
ERROR: 錯誤回傳碼(responseCode): 404 : http://comic101.com/vols/13321439/2
錯誤原因：
錯誤回傳碼(responseCode): 404 : http://comic101.com/vols/13321439/2

錯誤發生地點：
jcomicdownloader.tools.Common.errorReport(Common.java:171)
jcomicdownloader.tools.Common$Downloader.<init>(Common.java:3774)
jcomicdownloader.tools.Common.downloadFile(Common.java:855)
jcomicdownloader.tools.Common.downloadFile(Common.java:492)
jcomicdownloader.module.ParseCK.parseComicURL(ParseCK.java:141)
jcomicdownloader.module.RunModule.runSingle(RunModule.java:173)
jcomicdownloader.module.RunModule.runMainProcess(RunModule.java:70)
jcomicdownloader.module.Run.runSingleParseModule(Run.java:169)
jcomicdownloader.module.Run.run(Run.java:153)
jcomicdownloader.ComicDownGUI$7.run(ComicDownGUI.java:2486)
java.lang.Thread.run(Unknown Source)

**Comment by abc9070410** [comment]
已修復，請用最新版

https://github.com/abc9070410/JComicDownloader/releases/tag/v5.21.160815
