### ISSUE TITLE
無法下載

### ISSUE THREAD

**Issue by winnie7796265** [abc9070410/JComicDownloader#67]
http://www.fumanhua.net/manhua/1665/
http://www.fumanhua.net/manhua/3218/
http://www.cococomic.com/comic/30383/

都沒辦法下載耶...

**Comment by abc9070410** [comment]
fumanhua已修復，請用最新版
cococomic連線會顯示安全性錯誤，所以目前傾向不修復。

https://github.com/abc9070410/JComicDownloader/releases/tag/v5.21.160815
