### ISSUE TITLE
ex hentai無法下載

### ISSUE THREAD

**Issue by sivor0811** [abc9070410/JComicDownloader#68]
抓ex hentai上的東西的時候
都會顯示下載錯誤

**Comment by yamio** [comment]
雖然這回報有一陣子了。
我還是回一下我在除錯視窗上看到的敘述好了

寫出 X:\jdown\downloadList.dat 檔案
您的國家代碼是: TW
SET路徑：X:\jdown\set.ini
找不到com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel介面 !!

我猜大概是解析的網址跑掉吧(?)

**Comment by abc9070410** [comment]
已修復，請用最新版

https://github.com/abc9070410/JComicDownloader/releases/tag/v5.21.160815
