### ISSUE TITLE
8comic最新話不能下載

### ISSUE THREAD

**Issue by Archer515** [abc9070410/JComicDownloader#71]
所有最新話，8comic都會顯示紅色的最新話數都會下載錯誤
之前好像有看到他們跟改伺服器的通知

我雖然不是資訊相關，但是每天都會用這軟體下載已經四、五年了。
不知道及時問題回報會不會讓辛苦的開發者們備感壓力？

**Comment by abc9070410** [comment]
已經修復，請用下方版本:

https://github.com/abc9070410/JComicDownloader/releases/tag/v5.21.160820

還有歡迎及時回報問題，不會有壓力，因為我也是有時間才更新，哈。
