### ISSUE TITLE
很多無法下載

### ISSUE THREAD

**Issue by gigi421** [abc9070410/JComicDownloader#72]
http://www.99comic.com/
只顯示連線中,不能下載
http://www.fumanhua.net/manhua/4817/
第1話只顯示第1頁,所有話數都夾[老網址已經失效],但網頁上看是正常的
http://www.veryim.net/
以上是非常愛漫的新網址,能否將它更新?
它有比較齊的漫畫
http://www.dm5.com/manhua-wodeyingxiongxueyuan/
下載最新1話,但18頁只下載了11頁,中間出現缺頁

我也使用JD有2年了,但這個月發現連線和下載的速度比以前慢10倍以上,
請問能否了解一下問題所在?

**Comment by abc9070410** [comment]
fumanhua和veryim已經修復，請用下方的版本:

https://github.com/abc9070410/JComicDownloader/releases/tag/v5.21.160820

至於下載速度應該跟版本沒關係，跟你使用的網路比較有關..
可以用瀏覽器開看看速度是否跟Jcomicdownloader一致。

**Comment by gigi421** [comment]
感謝
那麼 http://www.99comic.com/ 能否修復?
這1年多也有使用99,但是這個月18號開始就不能使用
檢查記錄, 在10號前仍能下載

http://www.dm5.com/ 
有缺頁是否正常?

**Comment by abc9070410** [comment]
抱歉拖了很久，已經修復缺頁問題，請使用下方版本:

https://github.com/abc9070410/JComicDownloader/releases/tag/v5.21.160928
