### ISSUE TITLE
dm5

### ISSUE THREAD

**Issue by Noobungas** [abc9070410/JComicDownloader#74]
5.20算是最穩的，下載都沒缺頁，但最近無法下載了

5.21最新版的雖然能下載dm5，但會有缺頁，請處理一下~

**Comment by Kennyl** [comment]
可以嘗試在設定把timeout 加大。

2016年9月2日 23:38 於 "Noobungas" <notifications@github.com> 寫道：

**Comment by Noobungas** [comment]
沒用，11-18頁總是下載不了

**Comment by Noobungas** [comment]
能不能用5.20的程式改成能抓dm5就行，新版一直有不明缺頁

**Comment by abc9070410** [comment]
已經修復11-18缺頁問題，請用下方版本:

https://github.com/abc9070410/JComicDownloader/releases/tag/v5.21.160928
