### ISSUE TITLE
can't start in windows 10?

### ISSUE THREAD

**Issue by jinuuwu** [abc9070410/JComicDownloader#75]
Hi all,

I don't know why jcomicdownloader can't run in windows 10. I can use it before. I upgraded my windows version to the latest version in the beginning of Sept. Maybe it is the root cause. Can anyone tell me how to debug this problem?

Thanks.

**Comment by willngwy** [comment]
I can run on Windows 10; are you sure you installed correct Java JRE?

**Comment by hkgsherlock** [comment]
How it can't be used in Windows 10?

**Comment by jinuuwu** [comment]
My java version is Version 8 Update 101 which was reported from www.java.com. My windows 10 is version 1607 build 14393.105.

I execute jcomicdownloader.jar. But jcomicdownloader window doesn't appear. I also check the task manager. The javaw.exe well be runing after executing, but it is disappeared very soon.

How can I debug it?

Thanks.

**Comment by abc9070410** [comment]
Could you please try to execute JComicDownloader by Command Prompt as below ?
![image](https://cloud.githubusercontent.com/assets/2183861/18908391/fdd2ac28-85a1-11e6-87c2-25c50f0b3205.png)

And paste the log on the Command Prompt here, as below.
![image](https://cloud.githubusercontent.com/assets/2183861/18908475/4d726138-85a2-11e6-9202-399171ab6a3f.png)

Then we could analysis the problem on your Windows 10.

**Comment by jinuuwu** [comment]
Hi abc9070410,

Thank you for your help.

The jcomicdownloader GUI can appear when I execute "java -cp JComicDownloader-v5.21.jar jcomicdownloader.ComicDownGUI" from Command Prompt. But it can't appear when I click JComicDownloader-v5.21.jar. It is interesting.

The following is the log.
C:\Jinuu's Program\07_Network Utility\JComicDownloader>java -cp JComicDownloader-v5.21.jar jcomicdownloader.ComicDownGUI
JComicDownloader start ...
您的國家代碼是: TW
SET路徑：C:\Jinuu's Program\07_Network Utility\JComicDownloader\set.ini
找不到com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel介面 !!
設定檔全部讀取完畢
代理伺服器資訊欠缺位址或連接阜，因此不加入
將讀入書籤數量: 22   ... 讀入完畢!!
設置com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel介面
使用的cookie: ipb_member_id=0;ipb_pass_hash=NULL
Support Modules: [UNKNOWN, KUKU, EH, NINENINE_MANGA, NINENINE_COMIC, NINENINE_99770, NINENINE_COCO_TC, NINENINE_COCO, NINENINE_MH, NINENINE_1MH, NINENINE_3G, MANHUA_178, EIGHT_COMIC_PHOTO, EIGHT_COMIC, JUMPCNCN, DMEDEN, JUMPCN, MANGAFOX, MANMANKAN, XINDM, EX, GOOGLE_PIC, NANA, CITY_MANGA, IIBQ, BAIDU, SF, KKKMH, SIX_COMIC, MANHUA_178, KANGDM, BENGOU, EMLAND, MOP, DM5, CK, TUKU, IASK, NINENINE_MH_99770, JM, NINENINE_COMIC_TC, NINENINE_MANGA_TC, MANGA_WINDOW, CK_NOVEL, MYBEST, IMANHUA, VERYIM, WENKU, FUMANHUA, SIX_MANGA, XXBH, COMIC_131, BLOGSPOT, PIXNET_BLOG, XUITE_BLOG, YAM_BLOG, EYNY_NOVEL, ZUIWANJU, TWO_ECY, UUS8, NINENINE_MANGA_WWW, EIGHT_NOVEL, QQ_BOOK, SINA_BOOK, FIVEONE_CTO, ONESEVEN_KK, QQ_ORIGIN_BOOK, UUS8, WENKU8, IFENG_BOOK, XUNLOOK, WENKU7, WOYOUXIAN, SHUNONG, SOGOU, TING1, XIAMI, WIKI, PTT, ISHUHUI]
設置com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel介面
設置com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel介面
