### ISSUE TITLE
動漫之家解析失敗

### ISSUE THREAD

**Issue by weekqin** [abc9070410/JComicDownloader#78]
错误提示：
解析集数时发生错误！

错误原因：
String index out of range: -1

错误发生地点：
java.lang.String.substring(Unknown Source)
jcomicdownloader.module.Parse178.getVolumeTitleAndUrlOnMainPage(Parse178.java:1445)
jcomicdownloader.module.RunModule.runMainProcess(RunModule.java:97)
jcomicdownloader.module.Run.runSingleParseModule(Run.java:169)
jcomicdownloader.module.Run.run(Run.java:153)

漫畫地址：
http://www.dmzj.com/info/limingqianxiaodui.html

煩請提示，謝謝

**Comment by Peecehood** [comment]
只支援開頭為http://manhua.dmzj.com的網址。

**Comment by Kennyl** [comment]
網路連線太不穩定，連browser也連不倒完整的網頁（timeout）。
