### ISSUE TITLE
下載錯誤

### ISSUE THREAD

**Issue by teddybearkoo** [abc9070410/JComicDownloader#8]
我試著從好幾個不同的漫畫網站下載漫畫
Ex:  www.dm5.com
       comic.kukudm.com    ......
都不約而同出現下載錯誤
請教您如何解決
謝謝

**Comment by icearea** [comment]
請問您使用的版本是？

**Comment by Kennyl** [comment]
dm5.com 現在被判定成盜鏈，出了404圖

**Comment by teddybearkoo** [comment]
我使用的版本是v5.19

2015-06-22 10:38 GMT+08:00 icearea <notifications@github.com>:

**Comment by icearea** [comment]
我剛剛測試dm5.com的"食戟之灵"
並沒有出現404的狀況

**Comment by icearea** [comment]
在錯誤log中
http://manhua1025.107-181-249-122.cdndm5.com/10/9404/2071047_8066.png
少了一個"/"
正確應為http://manhua1025.107-181-249-122.cdndm5.com/10/9404/207104/7_8066.png

**Comment by teddybearkoo** [comment]
2015-06-22 13:25 GMT+08:00 icearea <notifications@github.com>:

> 我剛剛測試dm5.com的"食戟之灵"
> 並沒有出現404的狀況
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/abc9070410/JComicDownloader/issues/8#issuecomment-114009474>
> .
>

1	false	千面女郎	49	49	下載錯誤	http://www.dm5.com/m131503/####http://www.dm5.com/m127215/####http://www.dm5.com/m97885/####http://www.dm5.com/m87569/####http://www.dm5.com/m81	false	千面女郎	49	49	下載錯誤	http://www.dm5.com/m131503/####http://www.dm5.com/m127215/####http://www.dm5.com/m97885/####http://www.dm5.com/m87569/####http://www.dm5.com/m84264/####http://www.dm5.com/m79784/####http://www.dm5.com/m79783/####http://www.dm5.com/m11318/####http://www.dm5.com/m11317/####http://www.dm5.com/m11316/####http://www.dm5.com/m11315/####http://www.dm5.com/m11314/####http://www.dm5.com/m11313/####http://www.dm5.com/m11312/####http://www.dm5.com/m11311/####http://www.dm5.com/m11310/####http://www.dm5.com/m11309/####http://www.dm5.com/m11308/####http://www.dm5.com/m11307/####http://www.dm5.com/m11306/####http://www.dm5.com/m11305/####http://www.dm5.com/m11304/####http://www.dm5.com/m11303/####http://www.dm5.com/m11302/####http://www.dm5.com/m11301/####http://www.dm5.com/m11300/####http://www.dm5.com/m11299/####http://www.dm5.com/m11298/####http://www.dm5.com/m11297/####http://www.dm5.com/m11296/####http://www.dm5.com/m11295/####http://www.dm5.com/m11294/####http://www.dm5.com/m11293/####http://www.dm5.com/m11292/####http://www.dm5.com/m11291/####http://www.dm5.com/m11290/####http://www.dm5.com/m11289/####http://www.dm5.com/m11288/####http://www.dm5.com/m11287/####http://www.dm5.com/m11286/####http://www.dm5.com/m11285/####http://www.dm5.com/m11284/####http://www.dm5.com/m11283/####http://www.dm5.com/m11282/####http://www.dm5.com/m11281/####http://www.dm5.com/m11280/####http://www.dm5.com/m11279/####http://www.dm5.com/m11278/####http://www.dm5.com/m11277/####
2	false	妙廚老爹	113	113	下載錯誤	http://www.dm5.com/m174453/####http://www.dm5.com/m161278/####http://www.dm5.com/m147637/####http://www.dm5.com/m147636/####http://www.dm5.com/m147635/####http://www.dm5.com/m147634/####http://www.dm5.com/m147633/####http://www.dm5.com/m148264/####http://www.dm5.com/m148362/####http://www.dm5.com/m150983/####http://www.dm5.com/m150765/####http://www.dm5.com/m149453/####http://www.dm5.com/m148698/####http://www.dm5.com/m147620/####http://www.dm5.com/m147288/####http://www.dm5.com/m91106/####http://www.dm5.com/m91105/####http://www.dm5.com/m91104/####http://www.dm5.com/m91103/####http://www.dm5.com/m91102/####http://www.dm5.com/m91101/####http://www.dm5.com/m91100/####http://www.dm5.com/m91099/####http://www.dm5.com/m91079/####http://www.dm5.com/m91078/####http://www.dm5.com/m91077/####http://www.dm5.com/m91076/####http://www.dm5.com/m91075/####http://www.dm5.com/m91074/####http://www.dm5.com/m91070/####http://www.dm5.com/m91069/####http://www.dm5.com/m91068/####http://www.dm5.com/m91067/####http://www.dm5.com/m91066/####http://www.dm5.com/m91065/####http://www.dm5.com/m91064/####http://www.dm5.com/m91063/####http://www.dm5.com/m91059/####http://www.dm5.com/m91057/####http://www.dm5.com/m91056/####http://www.dm5.com/m91055/####http://www.dm5.com/m91054/####http://www.dm5.com/m91053/####http://www.dm5.com/m91047/####http://www.dm5.com/m8954/####http://www.dm5.com/m8953/####http://www.dm5.com/m8952/####http://www.dm5.com/m8951/####http://www.dm5.com/m8950/####http://www.dm5.com/m8949/####http://www.dm5.com/m8948/####http://www.dm5.com/m8947/####http://www.dm5.com/m8946/####http://www.dm5.com/m8945/####http://www.dm5.com/m8944/####http://www.dm5.com/m8943/####http://www.dm5.com/m8942/####http://www.dm5.com/m8941/####http://www.dm5.com/m8940/####http://www.dm5.com/m8939/####http://www.dm5.com/m8938/####http://www.dm5.com/m8937/####http://www.dm5.com/m8936/####http://www.dm5.com/m8935/####http://www.dm5.com/m8934/####http://www.dm5.com/m8933/####http://www.dm5.com/m8932/####http://www.dm5.com/m8931/####http://www.dm5.com/m8930/####http://www.dm5.com/m8929/####http://www.dm5.com/m8928/####http://www.dm5.com/m8927/####http://www.dm5.com/m8926/####http://www.dm5.com/m8925/####http://www.dm5.com/m8924/####http://www.dm5.com/m8923/####http://www.dm5.com/m8922/####http://www.dm5.com/m8921/####http://www.dm5.com/m8920/####http://www.dm5.com/m8919/####http://www.dm5.com/m8918/####http://www.dm5.com/m8917/####http://www.dm5.com/m8916/####http://www.dm5.com/m8915/####http://www.dm5.com/m8914/####http://www.dm5.com/m8913/####http://www.dm5.com/m8912/####http://www.dm5.com/m8911/####http://www.dm5.com/m8910/####http://www.dm5.com/m8909/####http://www.dm5.com/m8908/####http://www.dm5.com/m8907/####http://www.dm5.com/m8906/####http://www.dm5.com/m8905/####http://www.dm5.com/m8904/####http://www.dm5.com/m8903/####http://www.dm5.com/m8902/####http://www.dm5.com/m8901/####http://www.dm5.com/m8900/####http://www.dm5.com/m8899/####http://www.dm5.com/m8898/####http://www.dm5.com/m8897/####http://www.dm5.com/m8896/####http://www.dm5.com/m8895/####http://www.dm5.com/m8894/####http://www.dm5.com/m8893/####http://www.dm5.com/m8892/####http://www.dm5.com/m8891/####http://www.dm5.com/m8890/####http://www.dm5.com/m8889/####http://www.dm5.com/m8888/####http://www.dm5.com/m8887/####http://www.dm5.com/m8886/####

**Comment by hkgsherlock** [comment]
(see Pull request [#9](https://github.com/abc9070410/JComicDownloader/pull/9))

先試一下 [11e9736](https://github.com/abc9070410/JComicDownloader/blob/11e97368f2098e59add03233b8d1b71b195c60d4/dist/JComicDownloader.jar) 的這個

**Comment by hkgsherlock** [comment]
剛剛試過下載 DM5 的 [宅男腐女戀愛真難](http://hk.dm5.com/manhua-zhainanfunvlianaizhennan/) 之後還不愉快じゃない的
有問題再重開這個 issue 吧

**Comment by teddybearkoo** [comment]
Thank you for everyone who help me to solve this problem.
I've get start downloading those.
Thank you all again.

2015-06-22 22:04 GMT+08:00 Charles Poon (Puneyrf Cbba) <
notifications@github.com>:
