### ISSUE TITLE
e-hentai 下載錯誤無法下載

### ISSUE THREAD

**Issue by asus123456** [abc9070410/JComicDownloader#82]
目前e-hentai會顯示下載錯誤無法下載 請問是否會更新？

**Comment by Peecehood** [comment]
ParseEH.java
59: baseSiteURL = "http://g.e-hentai.org";
228: if ( lines[j].matches( "(?s).*http://\\d+.\\d+.\\d+.\\d+(?s).*" ) ) {
兩個需要修改

**Comment by yamio** [comment]
最近我也有發現過下載部分漫畫會出現交錯到別部內容的情形過。
另外就是不知道為什麼下載完，下次開啟軟體還是會有部分的名目在待下載。

**Comment by hkgsherlock** [comment]
我比較好奇這個 mod 還是否有當初般的存在需求

**Comment by abc9070410** [comment]
新版本已經修復eh
https://github.com/abc9070410/JComicDownloader/releases/tag/v5.30.180529
