### ISSUE TITLE
百度貼吧變得無法解析了

### ISSUE THREAD

**Issue by chtw31** [abc9070410/JComicDownloader#86]
不知道為何前幾日開始百度貼吧變得無法下載了
我下載下面兩個都顯示下載失敗...
https://tieba.baidu.com/p/4941848745
https://tieba.baidu.com/p/4978124556

**Comment by Peecehood** [comment]
圖片網址由"http://imgsrc.baidu.com/"變成"https://imgsa.baidu.com"

**Comment by chtw31** [comment]
感謝回答!!
不過#178行也要改嗎？

**Comment by Kennyl** [comment]
應該修正了。
