### ISSUE TITLE
Error fetching URL for downloading latest executable

### ISSUE THREAD

**Issue by cc85** [abc9070410/JComicDownloader#93]
Current Version: 5.21.170323

https://uploadpie.com/zuZEil
（擷圖網址 72 小時內有效）

**Comment by Kennyl** [comment]
請再試一次。

**Comment by cc85** [comment]
試很多次皆如此

錄影動畫圖檔：https://uploadpie.com/f9pRy3
（網址 72 小時內有效）

**Comment by Kennyl** [comment]
可能要下星期才有新版。

**Comment by Kennyl** [comment]
已更新。

**Comment by cc85** [comment]
謝謝！辛苦了！
